### ISSUE TITLE
Provide a windows dll in release?

### ISSUE THREAD

**Issue by landrix** [googlei18n/libphonenumber#1000]
Is it possible to provide a windows dll in every official release here on github? It would be very great.

**Comment by landrix** [comment]
https://github.com/googlei18n/libphonenumber/issues/74

**Comment by keghani** [comment]
@landrix what about #74? It asked for Windows instructions in the README, which have since been implemented.

**Comment by penmetsaa** [comment]
@landrix
Thanks for your inputs. However we don't actively maintain windows builds. And there is no plan in near future to automate dll release but would be able to accept a PR that has script to build dll file. To do so, we'd also need someone else in the open-source community to test it out and help with the review. Please see the [known Windows issues](FAQ.md#what-about-windows), maybe someone else there or in the [discussion group](https://groups.google.com/group/libphonenumber-discuss) could help. 

Even if you can't take action in the foreseeable future, please let us know (and this applies to anyone in the community as well) if you're intent on following up at some point, otherwise we'll have to close this as infeasible given current resources.

If it is feasible for you to build the dll on your own for every release, please check our instructions on  [Building the library on Windows
](https://github.com/googlei18n/libphonenumber/tree/master/cpp)

**Comment by landrix** [comment]
thanks, you can close this issue

**Comment by penmetsaa** [comment]
Sure landrix@ :)
Thanks so much for your inputs.
