### ISSUE TITLE
Guinea Equatorial number +240555402843 (muni carrier) should be valid

### ISSUE THREAD

**Issue by luishdez** [googlei18n/libphonenumber#1035]
Country/region affected: GQ ( Guinea)
Example number(s) affected: +240555402843, 555402842
The phone number range(s) to which the issue applies: 55540XXXX, +24055540XXXX
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile ( Carrier MUNI )
The cost, if applicable ("toll-free", "premium rate", "shared cost"): toll-free

Link: http://libphonenumber.appspot.com/phonenumberparser?number=555402840&country=GQ

**Comment by penmetsaa** [comment]
@luishdez 
Thanks for providing all the details!
We've accepted this issue and add 555 range in an upcoming release.

We are unable to find evidence that this new 55 range belongs to MUNI. 
If possible please provide any official evidence / online reference for same so that we can update carrier name as well.

**Comment by padmaksha** [comment]
Fixed in release 7.3.0
http://libphonenumber.appspot.com/phonenumberparser?number=%2B240555402843
