### ISSUE TITLE
Parse phone number from a single string

### ISSUE THREAD

**Issue by Ornolfr** [googlei18n/libphonenumber#1046]
How can I parse and check if is valid the phone number object given a String such as "+380955555555" in Java?

**Comment by padmaksha** [comment]
@Ornolfr

You can use our [demo](http://libphonenumber.appspot.com/) to check whether the giben phone number is valid or not.
Please find the  example of the number you provided  which is validated by our [demo]
(http://libphonenumber.appspot.com/phonenumberparser?number=%2B380955555555)

**Comment by Ornolfr** [comment]
@padmaksha 

Thanks for your answer.

I know how to create a phoneNumber object having 2 strings which contain code and number separately.
```
PhoneNumber phoneNumber = new PhoneNumber().setCountryCode(Integer.valueOf(code)
                .setNationalNumber(Long.valueOf(number));
```
As I cannot know what substring should I get from a single string, what am I looking for is to create this object from it. Could you include some code into your answer?

**Comment by lararennie** [comment]
From our front page:

String swissNumberStr = "044 668 18 00";
PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
try {
  PhoneNumber swissNumberProto = phoneUtil.parse(swissNumberStr, "CH");
} catch (NumberParseException e) {
  System.err.println("NumberParseException was thrown: " + e.toString());
}

In your example, you can replace "swissNumberStr" with your actual string, and you can safely use "ZZ" as the region code if the number always starts with a plus sign, since we can then work out the country.

I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
