### ISSUE TITLE
Support 95\d{6} as valid mobile prefix in Cameroon

### ISSUE THREAD

**Issue by kdeldycke** [googlei18n/libphonenumber#1051]
I just uncovered an issue with a mobile phone from Cameroon. One of my user provided a mobile phone number with the following template: `+237 95 xx xx xx`. I was able to verify the existence of the line by sending an SMS to it with a unique authentication code. So I've little doubts about the reality of the line.

The thing is, the current `libphonenumber` package claim the number to be possible but not valid. Instead, I expect it to be both possible and valid. 

I suspect this issue has something to do with numbering changes from 2014, as adding a `6` prefix let the number to be recognized as valid:

Kind | Format | Example | `isPossibleNumber()` | `isValidNumber()`
--- | --- | --- | --- | ---
Old number | `+237 95 xx xx xx` | [`+237 95 12 34 56`](https://libphonenumber.appspot.com/phonenumberparser?number=%2B237+95+12+34+56) | `True` | `False`
New number | `+237 6 95 xx xx xx` | [`+237 6 95 12 34 56`](https://libphonenumber.appspot.com/phonenumberparser?number=%2B237+6+95+12+34+56) | `True`| `True`

Here are more informations regarding Cameroonese numbers:
* https://en.wikipedia.org/wiki/Telephone_numbers_in_Cameroon
* http://www.itu.int/oth/T0202000024/en
* http://www.africt.com/2014/09/cameroons-new-telephone-numbering-scheme-.html
* http://www.wtng.info/wtng-237-cm.html

**Comment by padmaksha** [comment]
Thank you for taking the time to improve libphonenumber!
We've accepted this issue and will fix this in an upcoming release.
Can you just confirm what carrier you expect this mobile range 9X to be for?

**Comment by kdeldycke** [comment]
@padmaksha Thanks for your reply. Need to double check here but it looks like a number from the local Cameroonese branch of Orange.

**Comment by padmaksha** [comment]
Cameroon has migrated all their mobile numbers from eight digits to nine digits by adding 6 in the beginning on Friday, 21 November 2014.
We will not add these ranges because they were officially changed on Nov 2014 and it seems that all the reported numbers are accessible with the leading 6. Since we
already ended support for the parallel running six we aren't going to confuse matters by going backwards, these numbers could be turned off any day and it is only 
luck that they are still being redirected to the new numbers. 
We recommend you to reach out to all affected users if possible and get
them to confirm their new numbers with the 6 prefix (e.g. +237 6 95 12 34 56 rather than +237 95 12 34 56).

**Comment by kdeldycke** [comment]
OK, fair enough. Thanks for the update! :)
