### ISSUE TITLE
Where is keepCountryCodeSource?

### ISSUE THREAD

**Issue by Mortimer2013** [googlei18n/libphonenumber#1072]
I found comment in maybeExtractCountryCode that says country_code_source is populated only when keepCountryCodeSource is true, but I do not find it. What I can do to populate country_code_source is set keepRawInput true and then preferred_carrier_code is also populated. Is it OK to do so? I want to check whether a number is from default country. Now my way is to judge whether getCountryCodeSource() equals to  CountryCodeSource.FROM_DEFAULT_COUNTRY.
Thank you~

**Comment by lararennie** [comment]
Hi and sorry for the slow response!

I don't think you can check whether a number is from the default country or not. You can check whether it is *valid* for that country by first parsing it, and then calling isValidNumberForRegion. However:
a) It might be valid for that country, and for another country too - so you can't tell it is definitely from that country
b) Our definition of what a country or region is is based on CLDR, so things like Svalbard have their own region code: you probably want to consider a number from Svalbard as actually being from Norway. This is why we usually recommend isValidNumber instead.

Note if you want to distinguish between a number like "+64 3 331 6005" when parsing it from AU and "03 331 6005", where the first one is on purpose entered in international format, you could use parseAndKeepRawInput and then you can check getCountryCodeSource() to see whether we guessed the country code from the region provided (AU in this case) or from the fact that the user entered it with "+" in front.

I will close this since it doesn't seem to be an issue with the library.

Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
