### ISSUE TITLE
Validate 7338 in India

### ISSUE THREAD

**Issue by pravmahe** [googlei18n/libphonenumber#1074]
Hi Team,

Noticed API is returning false for belwo mentioned valid mobile numbers in India:
+91 7291829298, +91 7219603344

Let me know if any change is needed to validate them.

**Comment by kkeshava** [comment]
Hi,

Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the demo (instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by ketansabnis** [comment]
@kkeshava - there is an issue for newer numbers in India - For example, 7338910876. Its a valid number. With your latest version on the demo link you mentioned, it returns true for isPossibleNumber but false for isValidNumber.

**Comment by keghani** [comment]
We've accepted this issue and will fix this in an upcoming release.

**Comment by bhachech** [comment]
We are affected by this as well... specifically we need to confirm 7338 prefix is going to return isValidNumber to be 'true'.

Eager to see this being corrected in very near future. Please advise as to which release might include the fix.

**Comment by penmetsaa** [comment]
@bhachech
This fix is part of our release 7.3.1, which we are planning to release in couple of days.

**Comment by hargup** [comment]
@keghani @penmetsaa Thanks for the fix and please advice all the people dependent on your library to apply the fix as soon as possible. It appears that your library is used very widely and this bug has caused considerable trouble to me. I cannot update my recovery number in Google Account and place a "Cash on Delivery" order on Amazon because all of them say my number is not valid.

I also wonder why they need to so strict when validating a number, can't they trust the user that he/she will enter the right recovery number?

**Comment by penmetsaa** [comment]
Fixed in release 7.3.1:  https://libphonenumber.appspot.com/phonenumberparser?number=7338910876&country=IN

@hargup,
Thanks for your patience and inputs provided. For each release we announce at  libphonenumber-discuss@googlegroups.com. GitHub users get notifications for all the updates. Generally products opt for strict validation to ensure the number is genuine or not.

**Comment by keghani** [comment]
BTW to sign up to libphonenumber-discuss see https://groups.google.com/forum/#!forum/libphonenumber-discuss
