### ISSUE TITLE
German mobile phone number, country code added incorrectly

### ISSUE THREAD

**Issue by vruizext** [googlei18n/libphonenumber#1076]
```
2.3.0 :001 >  Phonelib.parse('+49175312997', 'DE').e164
 => "+4949175312997"
```
`(0)175312997` is a valid mobile phone number. Shouldn't the `+49` be detected as the country code? It shouldn't be added again in this case. 

In any case, I found a workaround:
```
2.3.0 :002 > Phonelib.parse('0049175312997', 'DE').e164
 => "+0049175312997"
```

Might be related to #376, even though here is the inverse case.

**Comment by lararennie** [comment]
This code doesn't look like our library? If I put your input into our demo, it works as expected - see it is parsed as country_code 49 and national_number 175312997. (We don't show you the e164 format since it's an invalid number, but it should work just fine.)

http://libphonenumber.appspot.com/phonenumberparser?number=%2B49175312997&country=DE

Note it is an invalid number: if you are using a different library maybe they do something on top for invalid numbers (e.g. strip the + and try again). If you aren't using our library directly, you need to file a bug with them instead.

Your "workaround" is unfortunately not the correct behaviour: +0049175312997 is completely invalid, not diallable and doesn't make sense.

**Comment by dlyongemallo** [comment]
This looks like ruby code? It looks like you're calling https://github.com/daddyz/phonelib which is pulling our data, but isn't using our code. You'll have to file an issue against that project.

**Comment by vruizext** [comment]
You're right @dlyongemallo, thank you for pointing that and sorry for the bother.
