### ISSUE TITLE
Validation issue with +49 7462 2043693220

### ISSUE THREAD

**Issue by vrlandau** [googlei18n/libphonenumber#1122]
Country/region affected (e.g., "US"): DE

Example number(s) affected ("+1 555 555-1234"): +49 7462 2043693220

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): ?

The cost, if applicable ("toll-free", "premium rate", "shared cost"): ?

Supporting evidence: We were able to call this number.

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B49+7462+2043693220)

**Comment by penmetsaa** [comment]
@vrlandau 
Thanks for reporting this issue.

We are able to find number +49 7462 2043693220 at http://www.yelp.com.au/search?find_desc=&find_loc=Blumenstr.+22%2C+78194+Immendingen%2C+Germany, but we are not able connect to this number. Is there any a typo?

This number is 14 digits long. As per below ITU notification (Page 96), 7462 range belongs to fixed line numbers in Immendingen and it can only be 6 to 11 digits long. We already support this. http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000510002PDFE.pdf

We are not able to find 14 digit 7462 numbers online / in official docs.
Please provide official evidence / any other working reference to support this range in libphonenumber.

**Comment by vrlandau** [comment]
The number has an extension part. That is why it is longer. I have been able to call this number and your API says it is a possible number.

**Comment by penmetsaa** [comment]
@vrlandau,
Thanks for mentioning this.
In case the input number have extension part also in it, there should some separator.
Ex: +49 7462 2043693x220 https://libphonenumber.appspot.com/phonenumberparser?number=%2B49+7462+2043693x220&country=DE

Separators that are supported by API are x, #, ~, ex, ext, ext. and , . 
Note: Some of the other characters are not supported because they might be used during formatting.

There should be some separator (x in above case) that says this (220 in above case) is the extension part. 
Otherwise API do know what is the extension part and try to parses the complete number as phone number.

**Comment by penmetsaa** [comment]
@vrlandau,
In the input +49 7462 2043693220 , can you please let us know what is the actual number and what is the extension.

**Comment by andyst** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need
more information). Please re-open if you respond so we pick up on it.
