### ISSUE TITLE
Consider Palestinian phone numbers which start from Israel country code (+972) to be valid

### ISSUE THREAD

**Issue by denis-zhdanov** [googlei18n/libphonenumber#1134]
Libphonenumber currently considers Palestinian phone numbers which start from Israel country code (+972) to be invalid. Example (java):

        String nationalNumber = "599613248";
        PhoneNumberUtil util = PhoneNumberUtil.getInstance();
        for (String countryCode : Arrays.asList("970", "972")) {
            String phoneNumber = countryCode + nationalNumber;
            Phonenumber.PhoneNumber parsedNumber = util.parse(phoneNumber, "PS");
            System.out.printf("phone number %s is %spossible%n",
                              phoneNumber, util.isPossibleNumber(parsedNumber) ? "" : "not ");
            System.out.printf("phone number %s is %svalid%n",
                              phoneNumber, util.isValidNumber(parsedNumber) ? "" : "in");
        }

Output:

phone number 970599613248 is possible
phone number 970599613248 is valid
phone number 972599613248 is not possible
phone number 972599613248 is invalid

However, it looks like it's perfectly possible to call Palestinian numbers with Israel country code:

https://en.wikipedia.org/wiki/Telephone_numbers_in_the_State_of_Palestine

The task is to adjust Palestinian meta-data to consider either 970 or 972 as valid country codes

**Comment by penmetsaa** [comment]
@denis-zhdanov
The problem here is Libphonenumber API not able to pick the region of the phone number because the number is not in international format ( + <CountryCode> <SubscriberNumber> ): you are missing the leading plus sign. In general, we accept a number if:

a) you have subscriber number only (599613248), and you specify the correct region (here either PS or IL would work) https://libphonenumber.appspot.com/phonenumberparser?number=599613248&country=PS

b) you put it in E164 format with the leading plus
+972599613248 and default region as PS: https://libphonenumber.appspot.com/phonenumberparser?number=%2B972599613248&country=PS
+970599613248 and default region as PS: https://libphonenumber.appspot.com/phonenumberparser?number=%2B970599613248&country=PS

c) you start with the country code but supply the right region.
970599613248 and default region as PS: https://libphonenumber.appspot.com/phonenumberparser?number=970599613248&country=PS

d) you start with the international dialling prefix / national dialling prefix for a particular number.

More details in [javadoc of parse() method](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2800).

As far as we understand you can't dial:
1. Palestinian number 599613248 in format "<IsraelCountryCode> <Subscriber_number>" from Israel and Palestinian authority. Ex: 972 599613248 (without + symbol).
2. Israel number 21234567 in format "<PalestinianCountryCode> <Subscriber_number>" from Israel and Palestinian authority. Ex: 970 21234567 (without + symbol).

We consider this working as intended.

Please feel free to reopen the issue if above two cases possible / in case of any other issue.
