### ISSUE TITLE
Validation issue with 0643631234 (TH)

### ISSUE THREAD

**Issue by singjie** [googlei18n/libphonenumber#1136]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): TH

Example number(s) affected ("+1 555 555-1234"): +66 643631234

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"):  +66 64XXXXXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=0643631234&country=TH)

**Comment by singjie** [comment]
Attached references: 

- http://www.bernumchok.com/home/show.php?selectPrefixNumber=064
- https://www.dropbox.com/s/ecm6wjrs7dgzplm/IMG_20160602_150116.jpg?dl=0

**Comment by penmetsaa** [comment]
@singjie,
Thanks for reporting this issue.

We can't connect to +66 643820273, +66 643631234 and 064-263-653 and are not able to find official evidence for the actual ranges that are valid. We need context about the prefix and length of the number that makes them valid. 

We found 64 range phone numbers also in http://kto.or.th/wp-content/uploads/2015/01/KOREA-THAI-113-122.pdf. We are not able to connect to any of these. Are these normal mobile numbers that are internationally dialable?

Please provide any official evidence for range 64 / references of any working numbers.

**Comment by penmetsaa** [comment]
Please see the [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence) for how to share evidence.

**Comment by singjie** [comment]
Hi @penmetsaa,

the number on the sim card, https://www.dropbox.com/s/ecm6wjrs7dgzplm/IMG_20160602_150116.jpg?dl=0 has been activated and can now be called through.

It has been an uphill task trying to locate evidence. Here's what we found, http://nbtcrights.com/cabinet-meetings/6281(Section 4.19) shows some information but it is in Thai.

**Comment by penmetsaa** [comment]
@singjie,
Thanks for providing the details.

We are able to connect to the number on the SIM card. We've accepted this issue (to add the 64 XXX XXXX range) and will fix this in an upcoming release.

Please let us know the carrier for this range and evidence that states the same since
we are unable to find it on the SIM card that you have shared.
There are no details present in http://nbtcrights.com/cabinet-meetings/6281 either.

We need more authoritative evidence to update the carrier details. Please check our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
@singjie 
Fixed in release in release 7.4.3
https://libphonenumber.appspot.com/phonenumberparser?number=%2B66+643631234

Updated carrier as 'Penguin SIM' as per the online evidences we found.
