### ISSUE TITLE
get country code from number prefix with international dialing prefix(IDD)

### ISSUE THREAD

**Issue by iammehrabalam** [googlei18n/libphonenumber#1165]
Is it possible to get the country code from number prefix with international dialing prefix(IDD)?
**Note: I don't know country from which number belongs to.**

example:  **009654835665**

00 --> international dialing prefix

**Comment by lararennie** [comment]
Do you know the country you are *dialling* from? If so, then just parse it with that region code. If not, then you're stuck because IDDs are shared, and overlap. So 00 is one, but 009 is also one. You could try parsing and validating the number from *every* country, and if it's valid then asking what country it's from, but this will be slow, and I suspect you'll have numbers where there are multiple possibilities.

I'll close this as it's not an issue with the library. Please consider joining
the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.
