### ISSUE TITLE
Validation issue with  +31 60 ddd ddd

### ISSUE THREAD

**Issue by jianping-roth** [googlei18n/libphonenumber#1177]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): 

Example number(s) affected ("+1 555 555-1234"):  +31 60 ddd ddd

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): 

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=+%2B31+60+189+147)

This is a valid Dutch phone number but was rejected.

**Comment by penmetsaa** [comment]
@jianping-roth 
Thank you for taking the time to improve libphonenumber!

We have found below official evidence that whole 60 mobile range is valid.
http://wetten.overheid.nl/BWBR0010198/2015-07-15

We've accepted this issue and will fix this in an upcoming release.

We were not able to find carrier details for this whole range.
Please share any supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article) so that we can update carrier details as well. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by jianping-roth** [comment]
Thank you for your prompt reply and I look forward to your update!
p.s. I wonder if you can help to hide the phone number please?

**Comment by penmetsaa** [comment]
@jianping-roth 
I have masked the phone number present in issue description.
As mentioned in earlier comment, can you please let us know the carrier for this 60 prefix and share any supporting documents?

**Comment by jianping-roth** [comment]
I don't know the carrier for this 60 prefix. We think it is a mobile phone code as per 
http://www.searchpeopledirectory.com/international-reverse-phone/31/

**Comment by lararennie** [comment]
Not a very reliable source unfortunately. The official docs think the prefix is mobile, but the length is wrong.

**Comment by jianping-roth** [comment]
While finding the carrier for you, we discovered this is not a valid number: we missed one digit. Please close this issue and 1178 as well.

**Comment by penmetsaa** [comment]
@jianping-roth,

Thanks so much for your investigation.
There are no valid numbers / official evidences for 8 digit 70 range phone numbers.
So as you suggested I have closed #1178. 

But we are able to connect to +31 60 189 XXX (8 digit 60 range phone number) that is shared by you.
As per below official document there can be only 9 digit mobile numbers in Netherlands.
http://wetten.overheid.nl/BWBR0010198/2015-07-15

So we have contacted Dutch numbering authority (info@mijnoverheid.nl) to get some clarifications. We are waiting for their response. https://www.overheid.nl/contact/

Closing this issue for now. Will re-open and update this issue based on response we get from them.
