### ISSUE TITLE
Implement call to important persons and organizations

### ISSUE THREAD

**Issue by afarsi** [googlei18n/libphonenumber#1188]
Hi there.
Recently xiaomi announced new release of MIUI(MIUI 8.0) globally. This is one of features of MIUI 8.0:

>The Caller ID feature will now show you who is calling, and also has contact details of popular businesses so you can call them even if you don't know their numbers. This also works in messages, which now identifies contacts with unknown numbers and if it's a message from a business, it shows a more user friendly brand name instead of an indecipherable string of letters.

But I want suggest a more useful and more general feature for libphonenumber:
With this feature, you can say "call police" and telephone will call to police, although the police number is not saved in your contacts.

Also if you say "call urgent" or say "call EMS", your phone can contact to "Emergency Medical Service", although the number of EMS is not saved in your contacts.

Also if you say "call sos", your phone can contact to 112 number.

In Addition, children can say "call to childcare" and phone contact to Family/Children Protection Service.

In addition you can add "call to persident" and phone can contact to President/prime minister office people relation service!

If you say "call fire" or "call Fire station", your phone can contact to Fire Emergency Service, although the Fire station number isn't in contacts.

I know this feature should be implemented in phone smart assistant, but I think an API in libphone number can help to implementing this feature in smart assistances.
In addition the authors of this project(libphonenumber) can request from Google to implement this feature in Android.
 
Thanks.

**Comment by penmetsaa** [comment]
@afarsi,

Thank you for taking the time to improve libphonenumber!

MIUI internally uses Android. They might have developed a wrapper to provide these add-on features (Phone smart assistant). This may be a nice feature to have within Android as well so that  all implementers can benefit out of it.

Please report the bug to Android [here](https://source.android.com/source/report-bugs.html). We would be happy to work with Android if they are interested. 

I'm closing this issue as it is not in the scope of Libphonenumber to implement this feature on its own. Thanks again for suggesting this to us.
