### ISSUE TITLE
Is libphonenumber.appspot.com kept updated with the latest release?

### ISSUE THREAD

**Issue by slaterkid** [googlei18n/libphonenumber#1196]
When a new version is released on github or on http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/ does that release also support what's on the web app?

**Comment by lararennie** [comment]
Hi, this is something that should be asked on the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) rather than opened as an issue.

Short answer: we update the demo and maven and github all at the same time usually: sometimes code-changes happen on github outside our usual "release" schedule though, but the demo and maven should be in sync.

I'll close this as it's not an issue with the library.
