### ISSUE TITLE
Why python phonenumbers library return empty string for country of +3587*****?

### ISSUE THREAD

**Issue by alirezastack** [googlei18n/libphonenumber#1198]
[The question](http://stackoverflow.com/questions/38281596/why-python-phonenumbers-library-give-null-for-country-of-358) was first asked on stackoverflow that numbers with `+3587` results an empty string, it is been said that it needs to be `+3589` to get `Finland`, but this number is a real purchased number, so it needs to be taken into account.

The code I ran:

```
>>> import phonenumbers
>>> from phonenumbers import geocoder
>>> query = phonenumbers.parse('+358753263***', None)
>>> number_country = geocoder.country_name_for_number(query, "en")
>>> number_country
u''
```

As you see the result is an empty string, but the number is actually for `Finland`. Is this a bug? Is there any workaround?

phonenumbers version: `7.4.4`

**Comment by alirezastack** [comment]
No one to answer the issue?

**Comment by penmetsaa** [comment]
@alirezastack 
Thank you for taking the time to improve libphonenumber!

We do not maintain [python port of libphonenumber](https://github.com/daviddrysdale/python-phonenumbers). This issue applies to main libphonenumber project also.

Libphonenumber is returning empty string because the number you are checking is not a geographical number, and furthermore, +358 is a multi-region country code. (Finland shares its country code +358 with Åland Islands). 

Since it is non-geographical, we end up resorting to a country name, but we don't know which one to choose. We could decide to return "Finland or Åland Islands" but the list will be long in case of NANPA regions (countries that use +1 as country code). We regret to say that this is working as intended and cannot do a region specific implementation for this case.

Please check [PhoneNumberOfflineGeocoder.java](https://github.com/googlei18n/libphonenumber/blob/master/java/geocoder/src/com/google/i18n/phonenumbers/geocoding/PhoneNumberOfflineGeocoder.java#L76).
