### ISSUE TITLE
Alphanumeric characters should not be allowed after the  Phone number

### ISSUE THREAD

**Issue by CharithFIT** [googlei18n/libphonenumber#1199]
1. go to the http://libphonenumber.appspot.com/ 
2. Add +687 201234 or as phone number and submit
Observed: Result from isValidNumber() is true
Expected: Result from isValidNumber() should be false

**Comment by penmetsaa** [comment]
@CharithFIT,
Thank you for taking the time to improve libphonenumber!
As per below official evidence 6 digit 20 range is assigned to fixed line numbers in New Caledonia.
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000980001PDFE.pdf

Please share any official evidence that say +687 20 XXXX numbers are no more valid. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by lararennie** [comment]
Charith: I think you meant that you added some alpha characters afterwards, based on the bug title? What was your actual input in that case?

**Comment by justechn** [comment]
I also ran into this problem. a53055a51212a, US country code, shows as a valid number, but very clearly is not

**Comment by lararennie** [comment]
We remove letters because "parse" is doing its best to extract a phone number out of the given text. If we think the number looks like a vanity number, we assume they are intentional and convert them to numbers accordingly. Please read the documentation for parse, and see #1001 and #328 for more background.

If someone fat-fingers and adds a random letter in the middle, then yes, we fix it for them. If they fat-finger and *replace* a digit with a letter, we'd consider the number invalid.

Closing this as working-as-intended.
