### ISSUE TITLE
readdir_r function definition not found

### ISSUE THREAD

**Issue by pnkjvvdy** [googlei18n/libphonenumber#1223]
I am trying to build libphonenumber cpp code using visual studio. generate_geocoding_data.cc file includes dirent.h header but in msvc dirent.h is not available.

I follow the all guidelines given in the document

**Comment by lo-re** [comment]
I have the same problem, all the dirent.h version found in internet do not provide readdir_r implementation

**Comment by pnkjvvdy** [comment]
@lo-re If you want to build cpp libphonenumber then you can build it without using geocoding library. It does not require dirent.h.

**Comment by penmetsaa** [comment]
@pnkjvvdy,

Thank you for taking the time to improve libphonenumber!

Yes, it is not possible to compile generate_geocoding_data.cc for Windows as it depends on the readdir_r() function which is not provided by Windows.

This issue is duplicate of #824 and it will be tracked there. So closing this issue.
We'd be happy if you can contribute to PR #1090 which is intended to solve this problem.
