### ISSUE TITLE
How to get the actual region code for numbers from DO,JM,GD, ...

### ISSUE THREAD

**Issue by patric-r** [googlei18n/libphonenumber#1225]
Is there a way to get the actual "region code" (iso 3166-1) for countries which share the same international prefix (country code in terms of libphonenumber)?

 e.g.  Number of Punta Cana airport (dominican republic): 
+1 809-959-2376

I need to get "DO".

Is this possible with libphonenumber (java)?

**Comment by alecx** [comment]
PhoneNumberUtil.getInstance().getRegionCodeForNumber(phonenumber);

**Comment by patric-r** [comment]
Almost perfect.
But it seems to have problems with NANPA toll free numbers outside US. e.g. Torontos airport number is  +1-866-207-1690 - but "US" is returned. If it's not possible to return the country of a NANPA toll free number, I'd expect an exception instead.

**Comment by penmetsaa** [comment]
@patric-r 
Thank you for taking the time to improve libphonenumber!

libphonenumber returns the correct region code for input “+1 809-959-2376”.
See demo: https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+809-959-2376
(we return as valid FIXED_LINE_OR_MOBILE number for region DO)

+1-866-207-1690, however, is a NANPA toll free number. See demo: https://libphonenumber.appspot.com/phonenumberparser?number=%2B1-866-207-1690

Since +1-866-207-1690 is non-geographical, we end up resorting to a country name, but we don't know which one to choose. We could decide to return "US or Canada or ..." but the list will be long. We regret to say that this is working as intended and cannot do a region specific implementation for this case.

Please check [PhoneNumberOfflineGeocoder.java](https://github.com/googlei18n/libphonenumber/blob/master/java/geocoder/src/com/google/i18n/phonenumbers/geocoding/PhoneNumberOfflineGeocoder.java).

Also see #1198 for a similar issue filed recently for Finland.

**Comment by patric-r** [comment]
@penmetsaa Thank you for your detailed answer.

There are use cases where "no region code could be determined" would be much better than a possibly wrong answer.

Maybe an overloaded method of `getRegionCodeForNumber()` would make sense which would return null (or an exception) in such cases. Or at least a check for `PhoneNumber` objects, something like `PhoneNumber.isNonGeographical()`.

When looking at the source, this should be fairly easy to implement.

**Comment by penmetsaa** [comment]
@patric-r 
Thanks for providing all the details we need! This sounds like a good idea.
We will add new API for this. However, metadata updates are the priority for us to ensure the data is fresh. We will get to this as soon as we have some free time.
