### ISSUE TITLE
Asia/Kolkata vs Asia/Calcutta

### ISSUE THREAD

**Issue by coreygeesey** [googlei18n/libphonenumber#1265]
The current response from libphonenumber when getting the timezone for an india number (country code: IN) is "Asia/Calcutta"

From my research, that city was renamed from Calcutta to Kolkata in 2001, and thus the timezone has been renamed to "Asia/Kolkata." This is also based on http://www.iana.org/time-zones

Is it possible to get it changed to Asia/Kolkata? Or are you guys pulling from a different data set?

Thank You

**Comment by padmaksha** [comment]
@coreygeesey 

Thanks for taking the time to improve libphonenumber!
We've accepted this issue.

We auto-generate the timezones, so we'll see if we can make a generic fix to this case.
(will take some time- just to manage expectations).

Thanks

**Comment by keghani** [comment]
We won't change the ID to `Asia/Kolkata` because we use [CLDR identifiers](http://www.unicode.org/cldr/charts/latest/supplemental/zone_tzid.html) which are stable. See their response at http://unicode.org/cldr/trac/ticket/9718.
The ID stays the same despite new aliases for this timezone, but you can use CLDR to find the localised name.

Thanks for reporting!
