### ISSUE TITLE
Local format - new field for Brazil

### ISSUE THREAD

**Issue by rzaryan** [googlei18n/libphonenumber#1301]
Domestic dialing in Brazil is more complicated than many other countries.

If a Brazilian person with a cell phone number of +553139561492 needs to call a friend with number +553135223131, then they must enter only 3522-3131 into their phone. That goes against the current "Domestic format" field in the libphone that returns (31) 3522-3131. The key difference is the removal of the prefix 31. If the caller has the same prefix of 31 as the number being called then the caller must omit the prefix for the call to be connected.

To solve for this, I suggest we create a new field in the libphone called Local format which provides a more specific phone formatting in the case where the person placing the call shares the same prefix the number being dialed.

Can others share their thoughts? Is this unique to Brazil? How do other developers work around this issue currently to ensure that local callers are able to connect successfully to local businesses in Brazil?

**Comment by lararennie** [comment]
This is not specific to Brazil, but is very hard to implement in other countries since in other countries it can be "in area code X this works, but not area code Y". We started a tag of area code optional in the XML file but haven't used it in many places, the idea being that we could expand the API one day and this information could help us return a phone number to dial given an input phone number.

We do support *formatting* numbers in this format (4-4) for Brazil but we don't have an API method that returns them like this. However you can do it yourself by asking for the length of the geographical area codes, comparing them, if they are identical dropping it if you want to (i.e. you are a mobile phone, in Brazil etc.)

We also have the formatForMobileDialling method but for Brazil this uses the preferred carrier code that was entered or returns nothing if none was. So this doesn't help much.

**Comment by keghani** [comment]
Since this is not an issue we're going to solve - @lararennie provided workaround above, and we don't have the data to solve it for every region - I'm closing as infeasible.
