### ISSUE TITLE
Martinique (MQ) validation issue

### ISSUE THREAD

**Issue by rneuter** [googlei18n/libphonenumber#1329]
Hi there,

I've got an issue with some [Martinique](https://en.wikipedia.org/wiki/Martinique) phone numbers. More details :

**Country/region affected :** MQ
**Example number(s) affected :** +596 6 96 53 26 00
**The phone number range(s) to which the issue applies :** +596-696-52-XX-XX -> +596-696-69-XX-XX
**The type of the number(s) :** I think fixed-line (cf ITU evidence below)
**Supporting evidence :** 

- [International Telecommunication Union](http://www.itu.int/itudoc/itu-t/number/m/mtq/73078_ww9.doc)
- [Failure Demo](https://libphonenumber.appspot.com/phonenumberparser?number=%2B596+696+53+26+00&country=MQ)

Thank you,
Best Regards,

**Comment by kkeshava** [comment]
Hi,

Thank you for taking the time to improve libphonenumber!

We can't connect to +596 6 96 53 26 00. Did you mean to ask for +596 5 96 53 26 00? 

As per the ITU evidence provided, fixed line numbers have prefix “+596 596” and mobile has prefix “+596 696”. We are already supporting fixed line numbers that belong to “+596 596 50 XX XX to +596 596 79 XX XX” range. 
Please share any publicly available phone numbers which work or evidence that you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by rneuter** [comment]
Hi,

I've got the official website where the phone number is host.

Supporting evidence :

- [Twinandgo](http://www.twinandgo.fr/#contact) (french website, but you can see the phone number)

I looked at the ITU evidence I provided before, and yes maybe is a typing error (and I dived in...).
I will ask to support team to get more informations from our client, I'll be back soon.

Meanwhile, can you check the phone number on the website ?

Thanks you,

**Comment by kkeshava** [comment]
Hi,

We were unable to connect to 0696 53 26 00 earlier given in http://www.twinandgo.fr/#contact through landline however we are able to connect to it through Mobile. 
 
We've accepted this issue and will fix this in an upcoming release. We will be adding prefix 69653 xxxx to mobile.


We were not able to find carrier details for this range. Please share any supporting evidence (for example, a national numbering plan, announcements from mobile carriers, news articles) so that we can update the carrier details as well. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

**Comment by penmetsaa** [comment]
Fixed in release 7.7.1: https://libphonenumber.appspot.com/phonenumberparser?number=%2B596+6+96+53+26+00
