### ISSUE TITLE
Use non-breaking space when formatting phone numbers

### ISSUE THREAD

**Issue by guerrillalg** [googlei18n/libphonenumber#1330]
We have faced the following problem with formatting phone numbers and further usage in the RTL texts:
When phone number is formatted to 0999 12 34 56 in the RTL text it would look like 56 34 12 0999. Text is being parsed and parts of the phone(codes, prefixes etc..) are being treated as separate words and thus, it is getting messed up.
As a solution, one should use "Non breakable space" instead of regular space.

So, an issue request is to replace regular space char with nbsp, which might be a big problem for backward compatibility, or at least to have ability to configure the letter that is used as a separator.

**Comment by lararennie** [comment]
Actually, the best solution is to have bidi markers around any formatted phone number - because even things like + and brackets can cause problems, depending. 

If you have html pages, you should use this approach:
https://www.w3.org/International/articles/inline-bidi-markup/

and explicitly set the phone number to ltr.

(Details on how to achieve this for the non-html use-case: https://www.w3.org/International/questions/qa-bidi-unicode-controls)
