### ISSUE TITLE
PhoneNumberOfflineGeocoder in javascript port?

### ISSUE THREAD

**Issue by avimar** [googlei18n/libphonenumber#1337]
Hi -- it seems the PhoneNumberOfflineGeocoder isn't available in the javascript version, and thus not available to nodejs, websites, etc.

Can it please be ported?

Thanks!

**Comment by lararennie** [comment]
We don't plan on porting this, because the vast amount of geocoding data means the size would be prohibitive. I would imagine you would rather want to solve this via a service which JS can call. We don't have any plans to create such a service, but you could use the Java or C++ libraries to create a service yourself.

**Comment by avimar** [comment]
I use it client-side with https://github.com/jackocnr/intl-tel-input

But even so, I use a small port to run with nodejs here: https://github.com/seegno/google-libphonenumber so I currently run the entire libphone server side.

**Comment by avimar** [comment]
The entire geocoding folder is about 11mb with all the languages, which gzips to about 2mb... much bigger than the basic utils of 200kb simply minified.

Despite that, with the proliferation of server-side JS making size largely irrelevant, what would be required to port this over? If I would write that and submit a pull request, would that be accepted or is this not something you want to maintain?

**Comment by lararennie** [comment]
Thanks for the offer! We'll have a chat and see what we think. Good point about JS being commonly used server-side these days.

**Comment by lararennie** [comment]
Okay: we are happy to review and accept a PR. Note that we try and have our ports mirror the Java as much as possible so keep comments, var names etc the same as much as possible. Any public methods that aren't implemented should be documented in the README as such.

The PR will also need to have:
-- tests
-- code to build the geocoding data files suitable for inclusion as JS (ideally following the same principle as java/c++ where a string that appears multiple times is represented only once and referred to instead of including it lots of times)

**Comment by avimar** [comment]
I'm trying to grok the build system... firstly just for the data. I'm thinking that transforming the data into a response in javascript is far simpler than actually fully integrating into the system.

Firstly, how does the geocoding data from `resources/geocoding/` become accessible? For java, it looks like it gets built -- into some sort of binary.
I know the other metadata gets transformed for JS, is there code already for transforming the geocoding data into JSON or just concatenating it?

**Comment by sahilkanani1812** [comment]
Is there any update on this??

Can i use geo-location and timezone mapper facility with Javascript/Node?? If so please reply...
