### ISSUE TITLE
How should I deal with the phone number with Exit code? 

### ISSUE THREAD

**Issue by vaibhavshrivastava** [googlei18n/libphonenumber#1394]
I am using the phone validation demo and I have observed that if I give phone number with exit code as input and if I give the original country name , libphoneNumbers returns invalid phone number. 
Whereas for default country if I give the country as the country of the exit code used then I get the correct validated response. 
How should I handle this if I want to give country programmatically ?

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

To verify a number using exit code, we should always give the corresponding country name to which the exit code belongs in the 'default country' column for eg. exit code of India - 00 so default country - IN see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=009731745003&country=IN)

We can validate the number using the E164 format (with ‘+’ rather than the exit code) and then it will work independently of what default country is passed to the library eg. Phonenumber - +919731xxxxxx and default country - US see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B919731745003&country=US)

**Comment by keghani** [comment]
I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
