### ISSUE TITLE
 Not validating New Numbers for India

### ISSUE THREAD

**Issue by Jayad** [googlei18n/libphonenumber#1415]
http://libphonenumber.appspot.com/phonenumberparser?number=8660447360&country=IN
http://libphonenumber.appspot.com/phonenumberparser?number=7980123638&country=IN

These are new Numbers in India.
Even with the latest 7.7.3 version of the PHP API, we are Seeing these numbers as isValidNumber() false.
Kindly look into.

**Comment by penmetsaa** [comment]
@Jayad ,

Thanks for providing all the details we need! We've accepted this issue and
will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by Jayad** [comment]
Please add and let me know the package version.

**Comment by penmetsaa** [comment]
Sure.. :)

**Comment by Jayad** [comment]
We do use this package and facing issues whenever a new vendor gets added as a client. 
Like Reliance JIO user base is quiet huge in India now and launched a month or two back.
How to avoid such cases where new numbers (series) are getting from Service Providers added. Can there be a contributor role?

**Comment by penmetsaa** [comment]
Hi Jayad,

What you did is right.
Once you verified in our demo that any valid number is marked as invalid, you can raise a bug from results page itself and provide supporting details to us. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

This issue is fixed in today's release 7.7.4
http://libphonenumber.appspot.com/phonenumberparser?number=8660447360&country=IN
In this release we added support for quite a number of Reliance Jio ranges based on evidences that we got.
