### ISSUE TITLE
Invalid TimeZonesMapper for 380 code

### ISSUE THREAD

**Issue by burunduk** [googlei18n/libphonenumber#1425]
Country/region affected: UA (Ukraine)
Example number(s) affected: +380671234567
The phone number range(s) to which the issue applies: +380XXXXXXXXX

> PhoneNumberToTimeZonesMapper Results
> Time zone(s)	[Europe/Bucharest]

Should be: [Europe/Kyiv]

According tzdata, Ukraine has three time zones:
380|Europe/Kyiv
38031|Europe/Uzhgorod (fixed-line code 31)
38061|Europe/Zaporozhye (fixed-line code 61)

**Comment by lararennie** [comment]
This is because Kiev goes to Europe_Eastern metazone, and in the CLDR data that we use to generate these mappings there is no override for Europe_Eastern territory="UA" to go to Europe/Kiev instead. I don't know why not; can you file a bug here instead? http://unicode.org/cldr/trac/newticket

This is the file with the data:
http://unicode.org/repos/cldr/trunk/common/supplemental/metaZones.xml

These are the regions with specific time-zone identifiers from the Europe_Eastern metazone. Note Bucharest is the fallback one:

<mapZone other="Europe_Eastern" territory="001" type="Europe/Bucharest"/>
<mapZone other="Europe_Eastern" territory="AX" type="Europe/Mariehamn"/>
<mapZone other="Europe_Eastern" territory="BG" type="Europe/Sofia"/>
<mapZone other="Europe_Eastern" territory="CY" type="Asia/Nicosia"/>
<mapZone other="Europe_Eastern" territory="EG" type="Africa/Cairo"/>
<mapZone other="Europe_Eastern" territory="FI" type="Europe/Helsinki"/>
<mapZone other="Europe_Eastern" territory="GR" type="Europe/Athens"/>
<mapZone other="Europe_Eastern" territory="JO" type="Asia/Amman"/>
<mapZone other="Europe_Eastern" territory="LB" type="Asia/Beirut"/>
<mapZone other="Europe_Eastern" territory="SY" type="Asia/Damascus"/>

**Comment by lararennie** [comment]
Hmm. Seems they were removed as markup, will try again :)

Europe_Eastern	001	Europe/Bucharest
Europe_Eastern	AX	Europe/Mariehamn
Europe_Eastern	BG	Europe/Sofia
Europe_Eastern	CY	Asia/Nicosia
Europe_Eastern	EG	Africa/Cairo
Europe_Eastern	FI	Europe/Helsinki
Europe_Eastern	GR	Europe/Athens
Europe_Eastern	JO	Asia/Amman
Europe_Eastern	LB	Asia/Beirut
Europe_Eastern	SY	Asia/Damascus

**Comment by keghani** [comment]
I'll close this as it's not an issue with libphonenumber and should be fixed in CLDR.
