### ISSUE TITLE
Validation issue for +12428011440

### ISSUE THREAD

**Issue by palodelincak** [googlei18n/libphonenumber#1472]
Hello,

number +12428011440 is marked as not valid, but user says it's valid Bahamas number.

http://libphonenumber.appspot.com/phonenumberparser?number=%2B12428011440

Country/region affected : Bahamas
Example number(s) affected : 12428011440
The phone number range(s) to which the issue applies : Unsure
The type of the number(s) : Unsure
The cost, if applicable: N/A
Supporting evidence - https://whoisnumber.net/242/801-1

**Comment by SumathiSundara** [comment]
Hi,

Thank you for taking the time to improve libphonenumber!

We can't connect to +12428011440.
We don't support any numbers starting with +12428.

Please help us find evidence of the type of these numbers, e.g. fixed-line or mobile. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

Please share any working numbers or official evidence you may have. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by palodelincak** [comment]
I was able to connect with +12428017626.

It looks like this phone number pattern belongs to www.bealiv.com. However I struggle to find some official document.

**Comment by SumathiSundara** [comment]
We were not able to connect to +12428017626, are you sure the number's dialable internationally? Please note that you don't need to give us an actually dialable number, other forms of evidence are also acceptable. In particular, to share private information, we advise you to sign the CLA and email our internal-only group (details in the [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

We checked www.bealiv.com and it does not contain phone numbers starting with +12428. What information led you to believe they own this range? News announcements could be evidence for example.

Please help us find official evidence of the type of these numbers, e.g. fixed-line or mobile. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by SumathiSundara** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need additional evidence, such as another example number which we can connect to or a doc by the government or the carrier which lists the range). Please re-open if you respond so we pick up on it.
