### ISSUE TITLE
 Validation issue with +25676XXXXXXX (UG)

### ISSUE THREAD

**Issue by samskeller** [googlei18n/libphonenumber#1476]
Country/region affected : UG

Example number: +256761694013

The phone number range to which the issue applies ("+256 76Y XXXXXX" where Y is 0-4):

The type of the numbers: mobile

Supporting evidence: Unfortunately no evidence except that this was supported in this library in 7.7.2. When 7.7.3 came out, these phone numbers were no longer recognized as valid. They are still not recognized as valid in 8.0.0

[link to demo](https://libphonenumber.appspot.com/phonenumberparser?number=256761694013&country=UG)

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

We can't connect to +256761694013. Could you recheck or provide any other number?

We were supporting the range 76[0-4] earlier because it was informed that they would be functional in near future but we did not find any evidence or working numbers online till date, so we decided to remove them.

Please share any working numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
Hi,
This issue is blocked on your or other GitHub contributors' input. Please help us find evidence that +256761694013 is valid, or provide an example number from a business website or similar. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by samskeller** [comment]
hi @kkeshava -- sorry for the delay (the holidays had me busy). And sorry for the bad numbers -- looks like I had bad information coming to me and that number range doesn't appear to be valid. I'll close this issue -- sorry for the mistake!
