### ISSUE TITLE
Validation issue for 8639203255(jio number)

### ISSUE THREAD

**Issue by ajaysaini95700** [googlei18n/libphonenumber#1478]
not validating this number 
i am  using latest package com.googlecode.libphonenumber:libphonenumber:8.0.0

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

We were not able to connect to 8639203255, it says that the telephone number does not exist. 

Please share any official or supporting evidence (for example, a national numbering plan, announcements from mobile carriers, news articles) so that we can update the range and the carrier details as well. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
Hi,
We are able to connect to 8639203255 now.

We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we may use, modify, reproduce, publicly display, and distribute the information in accordance with our open source policies. Please let us know if you did not intend to submit the information for such use.

We need evidence to update the carrier details for this range. Please share any supporting evidence (for example, a national numbering plan, announcements from mobile carriers, news articles) so that we can update the carrier details as well.

**Comment by kkeshava** [comment]
Fixed in release 8.0.1.

**Comment by Kaushik1502** [comment]
I am using 8.0.1 version. Still not fixed in 8.0.1 I think. I am passing 8240967637 and +91 as country code 

here is the code

```
public static boolean validateUsingLibPhoneNumber(String countryCode, String phNumber) {
        PhoneNumberUtil phoneNumberUtil = PhoneNumberUtil.getInstance();
        String isoCode = phoneNumberUtil.getRegionCodeForCountryCode(Integer.parseInt(countryCode));
        Phonenumber.PhoneNumber phoneNumber = null;
        try {
            phoneNumber = phoneNumberUtil.parse(phNumber, isoCode);
        } catch (NumberParseException e) {
            e.printStackTrace();
        }
        boolean flag = false;
        if (phoneNumber != null) {
            boolean isValid = phoneNumberUtil.isValidNumber(phoneNumber);
            if (isValid) {
                flag = true;
            } else {
                flag = false;
            }
        }
        return flag;
    }
```

**Comment by penmetsaa** [comment]
@Kaushik1502 ,
Please upgrade to the latest release, this is not a live issue. To check the
latest behavior for yourself, see the demo (instructions in our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by Kaushik1502** [comment]
got it @penmetsaa
