### ISSUE TITLE
Validation issue with UAE mobile number

### ISSUE THREAD

**Issue by johnnylai** [googlei18n/libphonenumber#1481]
Country/region affected (e.g., "US"): UAE
Example number(s) affected ("+1 555 555-1234"): "+971 57 1234567"
The phone number range(s) to which the issue applies ("+971 5X XXXXXXX"):
The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
The cost, if applicable ("toll-free", "premium rate", "shared cost"):
Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): page 19: http://www.tra.gov.ae/assets/eOKI3wmk.pdf.aspx

**Comment by kkeshava** [comment]
Hi,
Thank you for taking the time to improve libphonenumber!

We were not able to connect to +971 57 1234567. We already support 5[024-68] as mobile numbers. The national numbering plan provided by you mentions that it is reserved for mobile services, but allocated in blocks. Please provide evidence for the number blocks beginning with 57 which are allocated. 

Please share any official or supporting evidence (for example, a national numbering plan, announcements from mobile carriers, news articles) so that we can update the range and the carrier details as well. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
