### ISSUE TITLE
Implement AsYouTypeFormatter.inputDigit with position

### ISSUE THREAD

**Issue by Mr-Goldberg** [googlei18n/libphonenumber#1485]
Add the function 'String AsYouTypeFormatter.inputDigit(char nextChar, int position)', which will not append the 'nextChar' to the number, but will insert somewhere in the middle, at 'position'.
This function should also remember the position of the 'nextChar', which should be extracted then through 'int AsYouTypeFormatter.getRememberedPosition()', allowing to put cursor in place.

**Comment by penmetsaa** [comment]
@Mr-Goldberg ,
Thank you for using libphonenumber! 
We need some more time to reply to this, but we'll aim to get back to you in early January. Feel free to email libphonenumber-discuss to talk with the community though! Thanks for your patience!

**Comment by penmetsaa** [comment]
@Mr-Goldberg ,
Can you please let us know the use case? So that we know why you need this new API.

**Comment by Mr-Goldberg** [comment]
@penmetsaa 
Hi!
Sorry for such a long respond, I didn't see notification email.
The use-case:
User taps at the middle of the partially-entered number, and start to input more digits. Currently AsYouTypeFormatter can only append the digits, but the case is to insert them in the middle.
Like:
12_34
127_34 (user inputed '7' in the middle).

**Comment by penmetsaa** [comment]
@Mr-Goldberg,
Thanks so much for explanation :)

Android Dialer code handles this case without the proposed API being available. They pass in all the characters and the cursor position, rather than saying there was an "insert" at position 7 as you also need to handle a deletion at arbitrary positions too, and this way is more generic. 

Please take a look at the below java code and have similar implementation on your side as well. https://github.com/android/platform_frameworks_base/blob/master/telephony/java/android/telephony/PhoneNumberFormattingTextWatcher.java

As there is an alternative solution and [metadata](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#metadata_definition) updates being priority to us, we are not adding any overloading AsYouTypeFormatter APIs for this case.
