### ISSUE TITLE
Validation issue with +380713362477

### ISSUE THREAD

**Issue by z0mb1ek** [googlei18n/libphonenumber#1493]
****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: UA
Result from getNumberType(): UNKNOWN

****Formatting Results:**** 
E164 format: invalid
Original format: +380713362477
National format: 713362477
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid

It is valid UA number

**Comment by penmetsaa** [comment]
@z0mb1ek ,
Thank you for taking the time to improve libphonenumber!

We were able to conclude that 71 range phone numbers are valid in Ukraine. We are not able to find what type of numbers are these. Ex: fixed-line, mobile.. Please let us know the same and also share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by z0mb1ek** [comment]
https://en.m.wikipedia.org/wiki/Donetsk_People%27s_Republic this number is from

**Comment by penmetsaa** [comment]
@z0mb1ek,
I am not able to find any reference of 71 range phone numbers in above page.

**Comment by penmetsaa** [comment]
@z0mb1ek,
Can you please let us know what is the type of numbers are these. Ex: fixed-line, mobile..etc. Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by penmetsaa** [comment]
@z0mb1ek,
We already support 73 range phone numbers under mobile. So we guess this one also is a mobile range. We will go ahead and support 71 range numbers under mobile category.

If you think otherwise, please let us know so that we can update the library accordingly. If it is mobile range, please provide any supporting evidence (for example, a national numbering plan,
announcements from mobile carriers, news articles) so that we can update the
carrier details as well. 

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by z0mb1ek** [comment]
there is no official information, but there are many references at google, forums, etc.

**Comment by z0mb1ek** [comment]
71 range have http://phoenix-dnr.ru/

**Comment by kkeshava** [comment]
Fixed in release 8.0.1.

**Comment by z0mb1ek** [comment]
great work!
