### ISSUE TITLE
Validate 13-digit numbers in Canada

### ISSUE THREAD

**Issue by dw-tel** [googlei18n/libphonenumber#1515]
Hello,

http://libphonenumber.appspot.com/ say the number  +1 514 499 0159-107  is to long
But the on these Website is the number show https://www.goethe.de/ins/ca/en/ver.cfm?fuseaction=events.detail&event_id=20881596

The telephone number is extended by the telephone system, Can you include this number in the database with or what configuration I have to adjust

Kind regards
daniel

**Comment by keghani** [comment]
If 107 is an extension, the website is showing an incorrect format. Many tokens may be used to specify the extension, but `-` is not one of them, since it's used frequently for formatting (as are spaces and parentheses, and `+` is also special).
This number may be parsed by the library is entered in one of the following ways (this list is not exclusive):
*   [+1 514 499 0159#107](http://libphonenumber.appspot.com/phonenumberparser?number=%2B1+514+499+0159%23107)
*   [+1 514 499 0159x107](http://libphonenumber.appspot.com/phonenumberparser?number=%2B1+514+499+0159x107)
*   [+1 514 499 0159 ext. 107](http://libphonenumber.appspot.com/phonenumberparser?number=%2B1+514+499+0159+ext.+107)

If you reason to believe (other than its appearance on a website) that 13-digit numbers beginning with 514 should be considered valid in Canada, please provide more information and evidence according to our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md), and re-open the issue.

I'll close this as it's not an issue with the library. Please consider joining the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
