### ISSUE TITLE
Inconsistent result of isPossibleNumber() for too short French number

### ISSUE THREAD

**Issue by sylfabre** [googlei18n/libphonenumber#1539]
Steps to reproduce:
1. https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
2. Enter +3312345678 as phone number and press "Submit"

> Result from isPossibleNumber(): false
> Result from isPossibleNumberWithReason(): TOO_SHORT

3. Enter 012345678 as phone number and FR as country, then press "Submit"

> Result from isPossibleNumber(): true
> Result from isValidNumber(): false
> Phone Number region: FR
> Result from getNumberType(): UNKNOWN

Expected result:
- Results from step 3 should be the same as from step 2.
- 012345678 is not a possible French number as it is too short (missing 1 digit)

**Comment by lararennie** [comment]
This happens because when deciding whether to strip a national prefix or not, we look at what valid lengths are for this country, and if stripping the national prefix (0) would cause the number length to be wrong, we don't do so.
This means the first one is parsed as:
country_code	33
national_number	12345678

while the second one is parsed as:
country_code	33
national_number	12345678
italian_leading_zero	true

While this may seem a bit odd, you could compare to the US where the national prefix and country code is 1: people felt it was more intuitive for "1234567890" to be "possible" even though the 1 could be stripped, rather than stripping it and saying it was too short.

Note how we parse or interpret invalid numbers is less important to us than how we handle valid numbers: we just do a best guess.

What problem is this causing you?

**Comment by sylfabre** [comment]
@lararennie It's not a big deal as I am able to notify the user that the number he typed is wrong (`isValidNumber()` returns `false` for both) but the error message is not as accurate as possible.

I'm don't understand the parameter `italian_leading_zero` as my exemple is a French number.

In France, ten digits phone number must starts with a leading zero, nobody removes this zero as you may do in the US :-)

**Comment by lararennie** [comment]
2017-02-01 9:56 GMT+01:00 Sylvain <notifications@github.com>:

> @lararennie <https://github.com/lararennie> It's not a big deal as I am
> able to notify the user that the number he typed is wrong (isValidNumber()
> returns false for both) but the error message is not as accurate as
> possible.
>
> I'm don't understand the parameter italian_leading_zero as my exemple is
> a French number.
>
>  Yeah, it's badly named. Ignore "italian" and just think "leading_zero".

> In France, ten digits phone number must starts with a leading zero, nobody
> removes this zero as you may do in the US :-)
>
Well you do remove it in international format :)

Maybe we can make this more fine-tuned and see if the national prefix is
optional for a particular country. However there are short-codes in many
countries that start with the national prefix and to parse those correctly
we don't want to strip it. For example, in Australia you also have a 0 as a
national prefix, which is removed in international format. But the
emergency number is "000" so in this case we can't strip the first 0 and
say it is "00".

**Comment by sylfabre** [comment]
@lararennie I bet it's not that easy, we are already very lucky to have this library.
At least `isValidNumber()` works well, so fine-tuning would be nice if not too difficult to do!

**Comment by penmetsaa** [comment]
@sylfabre ,
Thanks for your kind words :) 
We will check this internally and get back to you.

**Comment by lararennie** [comment]
Okay, we've added a FAQ now explaining this, closing this as we aren't going to do anything more about this at this time.
