### ISSUE TITLE
Numbers are not supported: +917983045283, +918208621967

### ISSUE THREAD

**Issue by ashwinrkjain** [googlei18n/libphonenumber#1547]
Following numbers are valid Indian numbers
7983045283
8208621967

Please add them.

**Comment by penmetsaa** [comment]
@ashwinrkjain ,
Thanks for reporting this issue.

We already support 8208621967 as valid mobile number in India.
https://libphonenumber.appspot.com/phonenumberparser?number=8208621967&country=IN

Yes, we are not supporting 7983045283 as valid number. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

We were not able to find carrier details for this range.
Please share any supporting evidence (for example, a national numbering plan,
announcements from mobile carriers, news articles) so that we can update the
carrier details as well.

**Comment by kkeshava** [comment]
Fixed in release 8.3.0.
