### ISSUE TITLE
Invalid Indian Number series [709*]

### ISSUE THREAD

**Issue by vishnuku** [googlei18n/libphonenumber#1570]
This is not accepting any phone number starting with 709
For example below given numbers are valid Indian numbers
7093744536
7091744536

Please add this series.

**Comment by kkeshava** [comment]
@vishnuku,
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check the latest behavior for yourself, see the [demo](http://libphonenumber.appspot.com/phonenumberparser?number=7093744536&country=IN) (instructions in our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)).

**Comment by vishnuku** [comment]
Thanks a lot for quick response.

I am using python library for this. How do I incorporate this new changes to my side

Thanks & Regards
Vishnu Kumar
+91 9711296535

**Comment by vishnuku** [comment]
Thanks a lot for quick response.

I am using python library for this. How do I incorporate this new changes
to my side

Thanks & Regards
Vishnu Kumar
+91 9711296535 <097112%2096535>

On 14-Feb-2017, at 3:40 PM, kkeshava <notifications@github.com> wrote:

@vishnuku <https://github.com/vishnuku>,
Thank you for using libphonenumber!

Please upgrade to the latest release, this is not a live issue. To check
the latest behavior for yourself, see the demo
<http://libphonenumber.appspot.com/phonenumberparser?number=7093744536&country=IN>
(instructions in our contribution guidelines
<https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md>).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/libphonenumber/issues/1570#issuecomment-279664454>,
or mute the thread

**Comment by Onionz** [comment]
Hi,

I got similar issue that it failed to validate a valid number +918638440380. 

The carrier prefix is in the file [/resources/carrier/en/91.txt#L2316](https://github.com/googlei18n/libphonenumber/blob/ca1cf73590a536e8dbc1d5c5e0eae83c64968e1c/resources/carrier/en/91.txt#L2316). But the library determined this number as an invalid number.

**Comment by lararennie** [comment]
@vishnuku - You can talk to the owner of the py lib, he is great at maintaining the library so the problem should be solved there too if you update to the latest version.

@Onionz - Please open new issues for new prefixes so we can track them properly. However in this instance you can check the [Javascript demo](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) and see it is working there  - this is because we are in the middle of a release right now, so the Java demo is still showing 8.2.0 but the JS shows the new one already - so once the new release is on maven (hopefully today) you should get a fix for this prefix too.
