### ISSUE TITLE
Release notes have been deleted

### ISSUE THREAD

**Issue by thisislondon** [googlei18n/libphonenumber#1581]
Release notes lives at https://github.com/googlei18n/libphonenumber/blob/master/java/release_notes.txt
and have been deleted

Please note that a hyperlink still points to them at README.md

We rely on release notes, would be good to see them return.  Thanks!

**Comment by keghani** [comment]
Thanks for pointing out the outdated link in README.md!
I've sent https://github.com/googlei18n/libphonenumber/pull/1582 to fix this.
We moved the notes last week to the root directory since we include the entire repository under the release tag. They're now at https://github.com/googlei18n/libphonenumber/blob/master/release_notes.txt
