### ISSUE TITLE
UK phone number in local format incorrectly recognised as number with plus sign

### ISSUE THREAD

**Issue by dbarwacz** [googlei18n/libphonenumber#1583]
In 8.3.0 when phonelib is given uk number "07557 133631" with default country code "GB", then the metod `getCountryCode` on parsed number returns `FROM_NUMBER_WITH_PLUS_SIGN` while in fact it should return `FROM_DEFAULT_COUNTRY`. 

The problem does not exist on web demo (the result there is correct)

**Comment by lararennie** [comment]
The web demo *is* just using the library. Can you post some code?

**Comment by dbarwacz** [comment]
```
Phonenumber.PhoneNumber number = phoneNumberUtil.parse(phoneNumberStr, defaultCountryCode);
                        if (phoneNumberUtil.isValidNumber(number)) {
                            Phonenumber.PhoneNumber.CountryCodeSource source = number.getCountryCodeSource();
```
Do I use it correctly? It looks like `FROM_NUMBER_WITH_PLUS_SIGN` is the default value of the field, do I need to force it's refresh?
The environment I use is android.

**Comment by lararennie** [comment]
You are using the wrong method. You need to use parseAndKeepRawInput instead of parse.
Note that if you use parseAndKeepRawInput and want to compare numbers later, you'll have to use isNumberMatch, you can't use the "equals" method on the parsed objects, since they have information about the raw input itself.
