### ISSUE TITLE
Validation issue with +2127XXXXXXXX (MA)

### ISSUE THREAD

**Issue by yelouarma** [googlei18n/libphonenumber#1588]
Hello,

Numbers starting with 7, for example +2127XXXXXXXX  are now valid mobile number since January 2017.

National telecommunication regulation agency website:
[https://www.anrt.ma/infos-pratiques/ce-que-vous-devez-savoir/numerotation]( )

Thank you

**Comment by penmetsaa** [comment]
@yelouarma ,
Thank you for taking the time to improve libphonenumber!

The official evidence provided you mentions that mobile numbers starts with 1, 4, 5, 6 and 7. (This is at very broad level). The specific prefixes that are assigned to carriers are not mentioned here. Ex: https://www.anrt.ma/sites/default/files/blocs_de_numeros_par_operateur_juillet_2016.pdf

We need more information to fix this. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by yelouarma** [comment]
Hello,
Thank you for your reactivity :)
In the document you send, you can see bellow that numbers like 07XXXXXXX
are assigned to carriers since 07 august 2016 ( the red part).



2017-02-23 7:29 GMT+00:00 penmetsaa <notifications@github.com>:

**Comment by penmetsaa** [comment]
@yelouarma ,
It the PDF doc it is mentioned that following subfixes of 7 are assigned, not the complete 7XXXXXXX.
0700XXXXXX
0707XXXXXX
0761XXXXXX
0762XXXXXX
0770XXXXXX
0777XXXXXX
Can you please share us any working number or any online references. Please see our [contribution
guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by yelouarma** [comment]
Hello,

Here is the link to the press release:
https://www.anrt.ma/sites/default/files/rapportannuel/cp-prefixe-mobile-07-fr.pdf
An example of working number : +212 700150986



2017-02-23 9:13 GMT+00:00 penmetsaa <notifications@github.com>:

**Comment by penmetsaa** [comment]
@yelouarma ,
Thanks so much for providing the official announcement. As per this doc 07AB xxxxxx range is assigned to mobile and particular 07AB ranges will be further assigned to carriers. We consider only the ranges that are actually live/assigned to carrier as valid numbers. We can not consider whole 7XX XXXXXX as valid mobile range here.

As we are able to connect to the 700 XXXXXX number mentioned above, we would like to add 700 numbers under mobile category. Please provide us any evidence that mentions the carrier for this range. So that we can update carrier details as well.

If you found any other valid 7AB ranges that are considered as invalid by our library, please provide us a valid number / online references / evidences (these can be from carrier or numbering authority)

**Comment by penmetsaa** [comment]
@yelouarma,
We already support 700, 707, 761, 762, 770 and 777 mobile prefixes. Please let us know if there are any other valid 7AB ranges that are considered as invalid by our library. You can check our demo site. https://libphonenumber.appspot.com/

**Comment by penmetsaa** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
