### ISSUE TITLE
Validation issue with +917705012477 (IN)

### ISSUE THREAD

**Issue by manishbhatias** [googlei18n/libphonenumber#1589]
*   Country/region affected (e.g., "US"): IN
*   Example number(s) affected ("+1 555 555-1234"): +917705012477
*   The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): +9177xxxxxxxx
*   The type of the number(s) ("fixed-line", "mobile", "short code", etc.): mobile
*   The cost, if applicable ("toll-free", "premium rate", "shared cost"):
*   Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): https://libphonenumber.appspot.com/phonenumberparser?number=%2B917705012477

**Comment by penmetsaa** [comment]
@manishbhatias ,
Thank you for taking the time to improve libphonenumber! We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

We were not able to find carrier details for this range.
Please share any supporting evidence (for example, a national numbering plan,
announcements from mobile carriers, news articles) so that we can update the
carrier details as well. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by SumathiSundara** [comment]
Fixed in release 8.3.2.
