### ISSUE TITLE
Number Example of Mayotte

### ISSUE THREAD

**Issue by Mastersnes** [googlei18n/libphonenumber#1592]
Hi,

Mayotte country's id is +262 until July 2016 but the pattern example show "0269 60 12 34".

**Comment by lararennie** [comment]
The example number returned is a proto. To get a string like this you must
be formatting it in national format. If you want the country code, format
it in E164 or international format.... 269 is not there because we think it
is the country code....

Do you have some sample code? What version of the library are you using?

22. feb. 2017 5.38 p.m. skrev "Mastersnes" <notifications@github.com>:

Hi,

Mayotte country's id is +262 until July 2016 but the pattern example show
"0269 60 12 34".

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/libphonenumber/issues/1592>, or mute the
thread

**Comment by Mastersnes** [comment]
Ok, sorry for this ambiguity.
I made this mistake because the other country have a number example beginning with there country code (for example the number example of RE(Reunion) beginning with 0262).

For information, i use the libphonenumber javascript (stripped-down version) : https://github.com/halt-hammerzeit/libphonenumber-js

Thank for your response
