### ISSUE TITLE
Australia mobile number giving blank string from PhoneNumberOfflineGeocoder

### ISSUE THREAD

**Issue by rswheeldon** [googlei18n/libphonenumber#1602]
PhoneNumberOfflineGeocoder returns a blank string for Australian mobile phone numbers in the +614 ...
range.

e.g. https://libphonenumber.appspot.com/phonenumberparser?number=%2B61+412+345+678

**Comment by lararennie** [comment]
This is because we can't tell if it belongs to Australia, or to the other "regions" that share that country calling code (Christmas Island, Cocos Island etc).

We should add this to the docs of the public methods, not just the private one though :)

This is the same as issue #1198.

(Note we earlier returned the main country code, but there were complaints when we did this - see #586)

If you get an empty string, you can always get the region codes for the country code and then get their display name and do what you want with them. (getRegionCodesForCountryCode)

**Comment by rswheeldon** [comment]
But it does return the "AU" code but doesn't return Australia.

Compare for example:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B61+412+345+678
 (AU code under "Phone Number region" blank string under location)

Against:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B61+212+345+678
(AU code under "Phone Number region" but "Australia" under location)

**Comment by lararennie** [comment]
Different API, does something different. The Phone Number region *will* do the fallback to the "main" country code, but it's not intended for display. Same for this US toll-free number: https://libphonenumber.appspot.com/phonenumberparser?number=%2B18004563456 - shows US as the "most likely region", but it's problematic to claim it really is from there when displaying it to the user.

**Comment by rswheeldon** [comment]
Got it. Thanks.

**Comment by kkeshava** [comment]
Fixed in release 8.3.3.
