### ISSUE TITLE
Australian land line numbers lacking granular locations

### ISSUE THREAD

**Issue by rswheeldon** [googlei18n/libphonenumber#1604]
A number of phone numbers could be identified as being in specific cities based on public data but currently return only "Australia"

e.g. If we consider some of the numbers from Macquarie's office locations:
http://www.macquarie.com/au/about/office-locations

https://libphonenumber.appspot.com/phonenumberparser?number=%2B+61+7+5509+1400
Returns "Location" == "Australia" but it's in Brisbane, QLD, which we could tell from
https://en.wikipedia.org/wiki/Telephone_numbers_in_Australia#Central_East_region_.2802.29
 (or at least that it's Queensland)

https://libphonenumber.appspot.com/phonenumberparser?number=%2B+61+3+9864+2800
Returns "Location" == "Australia" but it's in Mebourne, which we could tell from
https://en.wikipedia.org/wiki/Telephone_numbers_in_Australia#South-east_region_.2803.29

Possibly because there's no resource for the region?

richard@kichemaru:~/github/libphonenumber$ find . -name "44.txt"
./resources/geocoding/en/44.txt
./resources/carrier/en/44.txt
./resources/test/carrier/sv/44.txt
./resources/test/carrier/en/44.txt
richard@kichemaru:~/github/libphonenumber$ find . -name "61.txt"
./resources/geocoding/en/61.txt
./resources/carrier/en/61.txt
richard@kichemaru:~/github/libphonenumber$ 

Happy to supply a patch if given a pointer to reasonable instructions on how to add the data / tests.

**Comment by mizuni** [comment]
Hi,

Apologies for the delay!

You're right - this is due to the lack of official resources for the region. See our
[guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence) in order check what type of sources we would need first.

Then see this GB example for how to contribute more granular locations, but check for more official metadata sources before starting: https://github.com/googlei18n/libphonenumber/blob/master/resources/geocoding/en/44.txt

**Comment by mizuni** [comment]
Hi @rswheeldon - we haven't received a response from you yet about getting some official sources for Australian geocoding. And was the pointer to an older pull request from another contributor sufficient?

**Comment by rswheeldon** [comment]
Not forgotten about this - just need to get round to it again.

**Comment by SumathiSundara** [comment]
Fixed in release 8.8.6.

**Comment by rswheeldon** [comment]
Definitely better. Thanks for this.
