### ISSUE TITLE
miss 388: Group of countries, shared code

### ISSUE THREAD

**Issue by jiafu1115** [googlei18n/libphonenumber#1630]
refer to https://www.itu.int/dms_pub/itu-t/opb/sp/T-SP-E.164C-2011-PDF-E.pdf

 @lararennie

**Comment by penmetsaa** [comment]
@jiafu1115 ,
We do not support all the country codes mentioned in ITU documents unless there are numbers assigned under that country code / do have numbering plan. Please take a look at our 
[FAQ page #why-are-bouvet-island-bv-pitcairn-island-pn-antarctica-aq-etc-not-supported](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.vmd#why-are-bouvet-island-bv-pitcairn-island-pn-antarctica-aq-etc-not-supported). Please provide us supporting evidences. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by jiafu1115** [comment]
@penmetsaa  so miss 388 is due to can't make one valid metadata description for the 388.
BTW, one question for it? where is the source file to generate /com/google/i18n/phonenumbers/data/PhoneNumberMetadataProto_800. I can't find it.
And is there possible to support 388 without one metadata proto. Then at least we can know it is valid country code(though it is shared by countrys).
Thanks

**Comment by penmetsaa** [comment]
(1) The source data is the main xml file  ([PhoneNumberMetadata.xml](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml).

(2) Yes, we don’t have 388 in our phone metadata ([PhoneNumberMetadata.xml](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml)) as there is no phone numbering plan available for it.  We auto-generate CoutryCodeToRegionCodeMap.java based on our phone metadata (PhoneNumberMetadata.xml) as we list only the region codes that we do have support for.

You can do a code change in your own port similar to your pull request #1628 but this is not recommended as you need to maintain your port up to date (in order to be up to date with phone numbering changes) and take care of the build as well - when we add new countries you have to merge.

What problem is this causing for you? Do you have diallable numbers with this country calling code?

**Comment by jiafu1115** [comment]
@penmetsaa Our application import the all E164's country codes and show it in web UI. So user can use it though I also doesn't know who will use and how to use. Thus I advice to support it without metadata to description it so that I will never encounter invalid country code for E164's 991 and 388. 
Whatever, Thanks for your feedback and I create one PR #1635 to avoid similar issues or questions asked.

**Comment by lararennie** [comment]
I think you probably *do* want to encounter that, we have never had any
user want to use them before :)

2017-03-16 4:16 GMT+01:00 stroller <notifications@github.com>:

**Comment by jiafu1115** [comment]
@lararennie  Thanks for your feedback!

**Comment by penmetsaa** [comment]
@jiafu1115 ,
We have updated our [FAQ page](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-are-bouvet-island-bv-pitcairn-island-pn-antarctica-aq-etc-not-supported) docs based on your inputs.
