### ISSUE TITLE
Allow for alternate MetadataManager implementations

### ISSUE THREAD

**Issue by tadfisher** [googlei18n/libphonenumber#1642]
On Android, `ClassLoader#getResourceAsStream` is slow and prone to concurrency issues. See this stacktrace snippet for an example of the latter:

```
Caused by java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
       at java.util.HashMap$KeyIterator.next(HashMap.java:814)
       at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:266)
       at java.util.jar.JarFile.getInputStream(JarFile.java:380)
       at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
       at java.net.URL.openStream(URL.java:470)
       at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
       at java.lang.Class.getResourceAsStream(Class.java:1169)
       at com.google.i18n.phonenumbers.MetadataManager$1.loadMetadata(MetadataManager.java:53)
       at com.google.i18n.phonenumbers.MetadataManager.getMetadataFromSingleFileName(MetadataManager.java:185)
       at com.google.i18n.phonenumbers.MetadataManager.getMetadataFromMultiFilePrefix(MetadataManager.java:116)
       at com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.getMetadataForRegion(MultiFileMetadataSourceImpl.java:64)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.getMetadataForRegion(PhoneNumberUtil.java:2127)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:2986)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.parseAndKeepRawInput(PhoneNumberUtil.java:2878)
       at com.google.i18n.phonenumbers.PhoneNumberUtil.parseAndKeepRawInput(PhoneNumberUtil.java:2867)
```

It would be very useful to allow for an alternate MetadataManager implementation which can load metadata from arbitrary locations, such as a file shipped as an Android asset in an APK.

Other libraries like Joda-Time and ThreeTenBP have similar issues, which has resulted in Android-specific libraries which wrap and replace their metadata-loading implementations:

- https://github.com/dlew/joda-time-android
- https://github.com/JakeWharton/ThreeTenABP

This is possible because those libraries allow for alternate implementations of their metadata loaders.

**Comment by keghani** [comment]
We have this I think? See [MetadataLoader](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataLoader.java), which you can pass in to a [PhoneNumberUtil.createInstance(MetadataLoader)](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L994).

Either way, what makes you say the concurrency issues would be due to getResourceAsStream? Could you elaborate on what Android and libphonenumber versions you're using?

**Comment by tadfisher** [comment]
@keghani My bad, I didn't see that bit of the API.

These issues seem to be prevalent on Android L and M; we haven't had any crashes on other versions yet. We're on libphonenumber 8.3.2 currently.

**Comment by tadfisher** [comment]
Hmm, looks like `DEFAULT_METADATA_LOADER` is hardcoded in a couple of places:

https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L83-L84

https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java#L91-L92

**Comment by MichaelRocks** [comment]
The default loader is still used for short numbers and alternate formats. Moreover, you still add metadata files to classes while on Android they should be in assets. I made fixes for this issues in my [fork](https://github.com/MichaelRocks/libphonenumber-android) of libphonenumber. However, it would be really nice to see these fixes in the original project.

**Comment by keghani** [comment]
It is for short numbers and alternate formats, because we don't have a similar option to initialize [ShortNumberInfo](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/ShortNumberInfo.java) and [PhoneNumberMatcher](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberMatcher.java) via a custom MetadataLoader like PhoneNumberUtil.

We currently don't do that for geocoding or prefixmapper either (https://github.com/googlei18n/libphonenumber/pull/577).

Is this important for you? I can see if the former is something I can do in the foreseeable future, but geocoding/prefixmapper are a bit more work so not sure about prioritization now.

**Comment by keghani** [comment]
@MichaelRocks thanks for the pointer! Is it possible for us to do this as a cross-platform library? We don't want to be used only in Android.

**Comment by tadfisher** [comment]
@keghani The best way to do this is to ship a metadata-less variant of the library, as Joda-Time and ThreeTenBP do, and to provide hooks for alternate MetadataLoader implementations so a third-party library can ship their own copies of the metadata in alternate formats.

**Comment by MichaelRocks** [comment]
Agree with @tadfisher. And I'm not sure it's possible to make the library cross-platform without breaking backward compatibility. At least I had to do that in my port.

**Comment by tadfisher** [comment]
Closing this as the original need has been satisfied. I'll log issues for supporting custom metadata loading for shortcodes and alternate formats.
