### ISSUE TITLE
Ireland, Germany and Nigeria Numbers digit restriction

### ISSUE THREAD

**Issue by sandheepraj** [googlei18n/libphonenumber#1657]
Hi,

Some of the series of numbers were failing in Ireland, Germany and Nigeria. Here are the failing scenarios:

Ireland - Arklow - +353 86 446 0784 = This has 9 digits and currently its letting to enter only 8 digits.
Ireland - Dublin -  +353 1 222 5550 = This works fine because it has 8 digits

Germany - Bad Homburg - +49 6172 9262148,  
Germany - Berlin - +49 30 22732152, 
Germany - Bonn - +49 228 9817525 - Here in these numbers digits has different length and which varies from 10-12 and current library is letting to enter more than 9

Also Nigera - Mobile numbers are +234 8080803431 current library accepts 9 digits but its throwing exception phone not valid for selected region (234) and its looking for 8 digits.

So here in this number it has 10 digits which the system is not letting to enter that. +234 8080803431

Also I have attached the spreadsheet which has what I have mentioned above.

Let me know

Thanks
Sandeep
[phonenos1 (002).xlsx](https://github.com/googlei18n/libphonenumber/files/866033/phonenos1.002.xlsx)

**Comment by lararennie** [comment]
They all seem to be valid for me.

Can you please check the demo?


23. mar. 2017 9.02 p.m. skrev "sandheepraj" <notifications@github.com>:

Hi,

Some of the series of numbers were failing in Ireland, Germany and Nigeria.
Here are the failing scenarios:

Ireland - Arklow - +353 86 446 0784 <+353%2086%20446%200784> = This has 9
digits and currently its letting to enter only 8 digits.
Ireland - Dublin - +353 1 222 5550 <+353%201%20222%205550> = This works
fine because it has 8 digits

Germany - Bad Homburg - +49 6172 9262148 <+49%206172%209262148>,
Germany - Berlin - +49 30 22732152 <+49%2030%2022732152>,
Germany - Bonn - +49 228 9817525 <+49%20228%209817525> - Here in these
numbers digits has different length and which varies from 10-12 and current
library is letting to enter more than 9

Also Nigera - Mobile numbers are +234 8080803431 <+234%20808%20080%203431>
current library accepts 9 digits but its throwing exception phone not valid
for selected region (234) and its looking for 8 digits.

So here in this number it has 10 digits which the system is not letting to
enter that. +234 8080803431 <+234%20808%20080%203431>

Also I have attached the spreadsheet which has what I have mentioned above.

Let me know

Thanks
Sandeep
phonenos1 (002).xlsx
<https://github.com/googlei18n/libphonenumber/files/866033/phonenos1.002.xlsx>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/libphonenumber/issues/1657>, or mute the
thread

**Comment by sandheepraj** [comment]
which demo you are referring to?

**Comment by lararennie** [comment]
http://libphonenumber.appspot.com

It's under the big "Demo" heading on our front page on github, in the
README.

23. mar. 2017 10.14 p.m. skrev "sandheepraj" <notifications@github.com>:

**Comment by keghani** [comment]
Yes, these are all valid with the latest version of the library.
Please read our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md), it discusses how to fix issues you may be having that are not due to our library (under "Is the issue reproducible using the demo?")

**Comment by latifaAkin** [comment]
The number +234-803-333-9806 is valid mobile MTN number is Nigeria, However in our test environment the total number in telephone field is written as (+234)80 333 398 instead of Original format	+234 803 333 9806( which is what you have in you demo app)....the number fields defined is inaccurate and does not take the entire mobile number......such is the case of the remaining countries mentioned in Sandeep's post

**Comment by lararennie** [comment]
Seems your environment is using an old version of the library then. You
need to update to the latest jars.

23. mar. 2017 11.04 p.m. skrev "latifaAkin" <notifications@github.com>:

The number +234-803-333-9806 <+234%20803%20333%209806> is valid mobile MTN
number is Nigeria, However in our test environment the total number in
telephone field is written as (+234)80 333 398 instead of Original format +234
803 333 9806 <+234%20803%20333%209806>( which is what you have in you demo
app)....the number fields defined is inaccurate and does not take the
entire mobile number......such is the case of the remaining countries
mentioned in Sandeep's post

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/libphonenumber/issues/1657#issuecomment-288874733>,
or mute the thread

**Comment by sandheepraj** [comment]
This is what we are using this is the latest version available right?

https://www.nuget.org/packages/libphonenumber-csharp/8.3.1.1 

Let me know

**Comment by keghani** [comment]
Hi @sandheepraj,

Sorry to mention this again, but did you read the [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md)?
In this case it looks like you should contact the other port. Please do read the guidelines, I think they have everything you need.

You can always see our latest release at the releases page. Just find it on the repository's home page; right now it says "50 releases" and if you click that link you get to https://github.com/googlei18n/libphonenumber/releases, and the latest is 8.3.3.

**Comment by sandheepraj** [comment]
when will the csharp library will get updated currently c# is still 8.3.1.1. Here is what I am refering to

https://www.nuget.org/packages/libphonenumber-csharp/
libphonenumber-csharp 8.3.1.1

when it will be updated to 8.3.3

Let me know

**Comment by lararennie** [comment]
Ask them, we don't manage it.
