### ISSUE TITLE
Validation issue with +16707837932

### ISSUE THREAD

**Issue by matthew-a-dunlap** [googlei18n/libphonenumber#1680]
Country/region affected (e.g., "US"): Mariana Islands

Example number(s) affected ("+1 555 555-1234"): +16707837932

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): 1670783XXXX

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Mobile

The cost, if applicable ("toll-free", "premium rate", "shared cost"): 

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): An account holder of ours @ Harvard University has this number yet it is rejected.

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We found evidence that +16707837932 is valid:

We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

We were not able to find carrier details for this range.
Please share any supporting evidence (for example, a national numbering plan,
announcements from mobile carriers, news articles) so that we can update the
carrier details as well. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by penmetsaa** [comment]
This is fixed as part of release 8.4.1
https://libphonenumber.appspot.com/phonenumberparser?number=%2B16707837932
