### ISSUE TITLE
Wrong international phone number for US country code.

### ISSUE THREAD

**Issue by jdflaugergues** [googlei18n/libphonenumber#1743]
There is a mistake in the international format for the US phone number.
In fact, a hyphen is missing between the phone code (+1) and the area code wheras this hyphen is expected according to the [RFC 3966](https://www.ietf.org/rfc/rfc3966.txt).

This issue is reproductible in the [Phone Number parse Demo ](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) with the number **15417543012** and the country code **US**.

**Observed output** : International format: +1 541-754-3012
**Expected output** : International format: +1-541-754-3012

**Comment by penmetsaa** [comment]
@jdflaugergues,

Thanks for using libphonenumber!

International and national formats are formatted as per ITU recommendations. If you would like to format the numbers in RFC3966 you need mention that (PhoneNumberFormat.RFC3966) while calling the format API.

```java
PhoneNumber phoneNumber = phoneUtil.parse("15417543012", "US");
String phoneNumberInRFC3966 =  phoneUtil.format(phoneNumber,  PhoneNumberFormat.RFC3966);
```

More details in [javadoc of these formats](
https://github.com/googlei18n/libphonenumber/blob/f9e9424769964ce1970c6ed2bd60b25b976dfe6f/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L384).

**Comment by penmetsaa** [comment]
I'll close this as it's not an issue with the library. Please consider joining
the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by jdflaugergues** [comment]
Thanks for your answer but I'm not satisfied.
First, I'm not using Java but Javascript, but anyway, this is all the format available with your library : 

National : (732)757-2923 
International : +1732-757-2923
E164: tel:+1-732-757-2923
RFC3966 : +1 732-757-2923

Neither of this previous formats corresponding to the international expected format : -1+732-757-2923.

**Comment by lararennie** [comment]
17. mai 2017 2.05 p.m. skrev "Jonathan de Flaugergues" <
notifications@github.com>:

Thanks for your answer but I'm not satisfied.
First, I'm not using Java but Javascript, but anyway, this is all the
format available with your library :

National : (732)757-2923
International : +1732-757-2923 <+1%20732-757-2923>
E164: tel:+1-732-757-2923 <+1%20732-757-2923>
RFC3966 : +1 732-757-2923 <+1%20732-757-2923>

These are not the outputs of our library. E164 has no formatting: that's
the RFC3966 result I think. You seem to be mixed up?

If you strip tel: (always there in the RFC3966 string) you'll get the
format you requested. (At least initially. It seems you have an error in
your last post).

Output should be the same in JS and Java. If it's not, that is a bug worth
reporting.

Neither of this previous formats corresponding to the international
expected format : -1+732-757-2923.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/libphonenumber/issues/1743#issuecomment-302069776>,
or mute the thread
