### ISSUE TITLE
Numbering Plan

### ISSUE THREAD

**Issue by eaba** [googlei18n/libphonenumber#1759]
Hello;
I am trying to make sense of your carrier prefixes for the United States.....Comparing with the list found here:https://www.numberingplans.com/index.php?page=plans&sub=phonenr&alpha_2_input=US&current_page=1 your carrier prefixes seems incomplete..
Can you enlighten me on why this is?

**Comment by lararennie** [comment]
They are not for the United States, they are from all countries with the country calling code 1.
We use publicly available data, which to date has mostly been available from the other countries covered by this file (e.g. ITU docs), not the United States itself.

We should make it clearer what the sources are though in a comment at the top of the file.

I'll close this as it's not an issue with the library. Please consider joining
the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd
like to discuss this further.

**Comment by eaba** [comment]
I understand that....What do make of the link I posted? Cant you work with it? I have applied to join group

**Comment by lararennie** [comment]
Doubt it:
See article five in their "legal" part:

You are not allowed to:
* collect or mine Materials and Services from our Website in an automated and/or a systematic fashion (database reverse engineering);
* republish Materials and Services from our Website, including republication on another website;
sell, rent or otherwise sub-license Materials and Services from our Website;
* copy, duplicate, adapt, edit or otherwise modify, change, transform, publish, republish, distribute, redistribute, broadcast, rebroadcast, reproduce, commercialise, make publicly available, show or play in public, or otherwise exploit Materials and Services from our Website;

**Comment by eaba** [comment]
Does this mean it cant also be used personally; not making it public?

**Comment by lararennie** [comment]
I'm not a lawyer. Please read the t&c of that site, and reach out to them if you have questions.
