### ISSUE TITLE
New Lao format

### ISSUE THREAD

**Issue by jonbom** [googlei18n/libphonenumber#1761]
We had complaints from a customer that claims he has the number:
+856 20 52\d{6}
Current metadata doesn't allow this.
Could someone please add this valid number pattern to Lao?

All needed is to change the `<mobile><nationalNumberPattern>` entry in PhoneNumberMetadata.xml to:

`<nationalNumberPattern>
          20(?:
            2[2389]|
            5[24-689]|
            7[6-8]|
            9[15-9]
          )\d{6}
        </nationalNumberPattern>`

**Comment by kkeshava** [comment]
@jonbom,
Thank you for taking the time to improve libphonenumber!
For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

We can't find official evidence for +856 20 52\d{6} being valid. We need more information to fix this.
We were not able to find carrier details for this range. Please share any supporting evidence (for example, a national numbering plan, announcements from mobile carriers, news articles) so that we can update the carrier details as well. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by jonbom** [comment]
@kkeshava 
They have no official proof of that. I have chatted with http://www.laotel.com/en/
and the only confirmed that so is the case but have no official document prooving the fact.
All +8562052xxxxxx numbers are valid mobile numbers.

**Comment by kkeshava** [comment]
This issue will be tracked in https://issuetracker.google.com/issues/62210500. Hence closing it.
