### ISSUE TITLE
zero not display on format partial french international phone number to national

### ISSUE THREAD

**Issue by jdflaugergues** [googlei18n/libphonenumber#1767]
Hi !

I have a bug when I try to format a **french** international phone number to a national phone number, the zero prefix is not display : 

Code to reproduce the bug:
```
import {PhoneNumberUtil} from 'google-libphonenumber';
var phoneUtil = PhoneNumberUtil.getInstance();
var number = phoneUtil.parseAndKeepRawInput('+336080424', 'FR')
phoneUtil.format(number, 2).replace(/ /g, ''); // output 6080424 instead of 06080424
```

This bug is reproductable on demo website with **+336080424** as phone number and **FR** as country code: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Have you got some fix ?

Thanks.

**Comment by lararennie** [comment]
Indeed, as you hinted when you said "partial":

Result from isPossibleNumber(): false
Result from isPossibleNumberWithReason(): TOO_SHORT

We don't know whether to attach a national prefix or not if the number is not valid, because then it could be a short-code, where the national prefix is inappropriate, so we don't modify it. We only focus on formatting valid numbers.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further (e.g. explain why you think this is important to support).

**Comment by jdflaugergues** [comment]
I'm disagree because a short-code doesn't have a country code prefix. So, for a phone number beginning b y a country code it can't be a short-code and it should be formatted correctly with the national prefix.
Moreover, **AsYouTypeFormatter** can give us the correct format (without national prefix) for an invalid phone number just passing the country code.

**Comment by lararennie** [comment]
Yes, but when we parse, we don't know anymore that you supplied a country code prefix. So the number we are formatting doesn't have that information, it is agnostic of original context.

(Also: some people provide short-codes with country code prefixes when parsing, for various reasons).

The AsYouTypeFormatter is designed for partial numbers.
