### ISSUE TITLE
Validate 50\d{9} in KR

### ISSUE THREAD

**Issue by ray424** [googlei18n/libphonenumber#1787]
The number starting with (' 50 ' or '050') is currently accepting only 10 digits.
but, it is currently policy changed to max 11 digits.

- libphonenumber
  1. valid : +82 5072331233
  2. valid : +82 05072331233
  3. invalid : +82 50712331233
  4. invalid : +82 050712331233
- korean telecom currently policy
  1. valid : +82 5072331233
  3. valid : +82 05072331233
  2. valid : +82 50712331233
  4. valid : +82 050712331233

**Comment by SumathiSundara** [comment]
We can't connect to +82 50712331233.

We support 10 digit long numbers for the prefix 50 while the specified number is 11 digits long.

Closing this as WAI; if you would like to reopen, please share any working
numbers or official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by keghani** [comment]
From dupe:

#1787 reopen.

working phone number is below.

+8250714128963
+8250714160067
please check it. thanks.

**Comment by keghani** [comment]
Other example from title:

+8250712451245

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!
 
We tried the given numbers and received "The number you just called hasn't been assigned" from Switzerland and a similar message from India.
 
Depending on the region one dials from, +8250714128963 could be connecting to the same number without the last digit, i.e. +825071412896. We don't know how different regions' carriers could be correcting the number. However we cannot connect to such numbers from Switzerland and India.
 
Please see our guidelines for [providing evidence](http://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).
 
In particular, we request a publicly available URL or that you sign the CLA and
(after getting whitelisted) share non-public evidence with the mailing list only
readable by core team members.
 
Please note that in this case an example number that connects will not suffice, since we're not sure whether the old numbers are migrating to the new ranges, or this is a new range altogether. We need official documentation.

**Comment by SumathiSundara** [comment]
We haven't received a response from you yet about official documentation.
Would it be possible for you to provide an update in order for us to move
forward with fixing this issue?

**Comment by SumathiSundara** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). 
Please re-open if you respond so we pick up on it.
