### ISSUE TITLE
Validation issue with +601162067687

### ISSUE THREAD

**Issue by valerio-brew** [googlei18n/libphonenumber#1839]
Please read the "guidelines for contributing" (linked above) and fill in the template below.

Country/region affected (e.g., "US"): MY

Example number(s) affected ("+1 555 555-1234"): +601162067687

The phone number range(s) to which the issue applies ("+1 555 555-XXXX"): N/A

The type of the number(s) ("fixed-line", "mobile", "short code", etc.): Supposedly a mobile number

The cost, if applicable ("toll-free", "premium rate", "shared cost"): mobile/national call

Supporting evidence (for example, national numbering plan, announcement from mobile carrier, news article): **IMPORTANT - anything posted here is made public. Read the guidelines first!** 

[link to demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B601162067687)

**Comment by penmetsaa** [comment]
@valerio-brew,

Thank you for taking the time to improve libphonenumber!

We found evidence that +60 116 XXX XXXX is valid mobile range.
We've accepted this issue and will fix this in an upcoming release. For your 
next metadata issue,  we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use. 

We were not able to find carrier details for this range.
Please share any supporting evidence (for example, a national numbering plan,
announcements from mobile carriers, news articles) so that we can update the
carrier details as well.

**Comment by cheowlihbin** [comment]
@penmetsaa ,

the following are the supporting evidence 

https://www.mcmc.gov.my/skmmgovmy/media/General/pdf/Mobile-Numbers-(3-8)-2017.pdf

**Comment by penmetsaa** [comment]
@cheowlihbin ,
Thanks for providing all the details we need! We've accepted this issue and will update carrier details in an upcoming release.

**Comment by penmetsaa** [comment]
This is fixed in release 8.7.0
https://libphonenumber.appspot.com/phonenumberparser?number=%2B601162067687

Carrier updates will be done in an upcoming release.

**Comment by penmetsaa** [comment]
Carrier updates are in 8.8.1
