### ISSUE TITLE
Method hasValidCountryCallingCode

### ISSUE THREAD

**Issue by tsaisean** [googlei18n/libphonenumber#1842]
Can make the `hasValidCountryCallingCode` method public?
Would like to use it to check the country calling code is valid or not.
eg. 
`hasValidCountryCallingCode(65) // return true as it's a SG calling code.`
`hasValidCountryCallingCode(886) // return true as it's a TW calling code.`
`hasValidCountryCallingCode(0) // return false as it's a unknown calling code.`

**Comment by lararennie** [comment]
Hi,

First of all: if you parse a number, you will *never* get an invalid country calling code, because we will throw an error instead.

Second of all: if you want to check a random country calling code, you can already do this with getRegionCodeForCountryCode -> if this is ZZ then it's invalid. So it's a one-liner already on your side. Given this, we'd rather not expand the API surface anymore at this time (it's already too large!)

Thanks though for the suggestion! Closing this as not something we will do for now.
