### ISSUE TITLE
Validation issue with +359 996 09 5556 (BG)

### ISSUE THREAD

**Issue by Darkov3** [googlei18n/libphonenumber#1905]
After looking at the meta data I saw this comment in the Bulgarian section:
https://github.com/googlei18n/libphonenumber/blob/98cb04aced00f7cb1b2af7993edbc0e7610141ed/resources/PhoneNumberMetadata.xml#L2975
https://github.com/googlei18n/libphonenumber/blob/98cb04aced00f7cb1b2af7993edbc0e7610141ed/resources/PhoneNumberMetadata.xml#L2976

It removes the 99/d{7} validation for Bulgarian national numbers.
But we have a real life case with a client who has this as a number: '+359 996 09 555x'
The library does not validate it as valid, as expected.
We have made a special case handler for our application, but it should be updated in the meta data too.

**Comment by keghani** [comment]
Thanks for reporting @Darkov3!

We need more information to fix the issue, such as what type you expect the range to be, which prefix (all of 99\d{7} or just 996), and official evidence for this prefix. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by Darkov3** [comment]
@keghani 
I have no hard evidence that other numbers ranges also exist, but I believe that if this one does, probably the rest also do, as they are defined by the ITU doc.
I have edited my OP to change the number slightly, due to possible privacy issues.

*   Country: Bulgaria
*   Example number(s) and/or range(s): +359 99* ** **** (+359 996 09 555x ; + 359 99/d{7}) (Include the entire 99\d{7})
*   Number type ("fixed-line", "mobile", "short code", etc.): mobile
*   For short codes, cost and dialing restrictions: -
*   Where or whom did you get the number(s) from: At work one of our clients tried to input their mobile number, but could not.
*   Authoritative evidence (e.g. national numbering plan, operator announcement): 
1. In the comment of your source code
2. CRC(COMMUNICATIONS REGULATION COMMISSION): http://www.crc.bg/files/_en/bulgarian_NNP-en-2014(ver..2016).pdf (at the bottom)
3. The ITU links to the above document as well: https://www.itu.int/oth/T0202.aspx?parent=T0202
*   Link from demo (http://libphonenumber.appspot.com) showing error: http://libphonenumber.appspot.com/phonenumberparser?number=%2B359+996+09+5552 (says that the number is not valid, but it is, as its a real number, with only one number changed at the end, for privacy issues)

**Comment by penmetsaa** [comment]
@Darkov3 
Thank you for taking the time to improve libphonenumber!

We found evidence that 996 is valid. We've accepted this issue and will fix this in an upcoming release.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

We were not able to find carrier details for this range.
Please share any supporting evidence (for example, a national numbering plan,
announcements from mobile carriers, news articles) so that we can update the
carrier details as well.

**Comment by Darkov3** [comment]
@penmetsaa 
To my knowledge, there is no carrier details aviable, but I did not do a completely extensive research.

**Comment by kkeshava** [comment]
Fixed in release 8.8.0.
