### ISSUE TITLE
Long but valid New Zealand numbers fail

### ISSUE THREAD

**Issue by bruceconlon** [googlei18n/libphonenumber#1949]
Mobile numbers starting with 29 should pass, eg: 2978102356 or 029-7501-9360

08965 852 1023 as a toll number should also pass

**Comment by bruceconlon** [comment]
Also, mobile numbers such as (022) 780 2156 format correctly to 022 780 2156 using phoneUtil.format(number, PNF.NATIONAL)

However 210455015 or 0210455015 become 0210 455 015 but should be 021 045 5015 as above

**Comment by penmetsaa** [comment]
@bruceconlon,
Thanks for using libphonenumber library.

We are not able to connect to 29X mobile and 896X toll-free numbers that you have shared. We are following the official ITU doc for mobile NZ numbers, except for the 21 prefix for which we found (and verified) online numbers.  https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000990001PDFE.pdf

Please share any working number along with official evidences so that we know range and category details. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

We are already formatting 022 780 2156 in the way you have proposed.
See our demo: https://libphonenumber.appspot.com/phonenumberparser?number=%28022%29+780+2156&country=NZ

Regarding changing of format 0210 455 015 to 021 045 5015, we're looking further into the formatting change, researching the reasons for the formatting rules we currently have for these prefixes. We will update this accordingly.

**Comment by bruceconlon** [comment]
Ok thanks, have written to both itu and the NZ Ministry of Economic Development to se if they can publish an update for you

**Comment by penmetsaa** [comment]
This issue is blocked on your or other GitHub contributors' input. Please help
us find evidence that 29X mobile and 896X toll-free numbers are valid, or provide an example number from a business website or similar. Otherwise we don't have enough information to
fix the issue and may have to close it as infeasible.

@bruceconlon,
Any response from  ITU or the NZ Ministry of Economic Development?
If no, could you please ping them on the mail you have sent?

**Comment by penmetsaa** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). Please re-open if you respond so we pick up on it.
