### ISSUE TITLE
Number pre appended by 0 fails validation

### ISSUE THREAD

**Issue by lokeshagrawal83** [googlei18n/libphonenumber#1951]
For eg: for US, number 555-555-5555 passes the validation. But 0555-555-5555 fails the validation. Also 1555-555-5555 passes the validation, because US's dialing code is 1. Is it possible to do something about it. 

Removal of pre 0s seems like an easy fix.

**Comment by penmetsaa** [comment]
@lokeshagrawal83,
Thanks for using libphonenumber! 

The input phone number has to be in right dialling format in order to parse the number right. In this case 0 can not be trimmed off as 1 is the national prefix for the USA as you already mentioned.

I'll close this as it's not an issue with the library.

**Comment by penmetsaa** [comment]
Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
