### ISSUE TITLE
make getRegionCode return 'ZZ' instead of null when the region code is not known

### ISSUE THREAD

**Issue by perezsaint** [googlei18n/libphonenumber#1968]
I think this could be a welcomed change to avoid NPEs for people using this library. I don't think it makes much sense to return null values when we literally have a region code called 'UNKNOWN_REGION'. 
If you guys think this is a good idea, I could open a PR with this change.

**Comment by keghani** [comment]
Thanks for reporting @perezsaint!

I think you're referring to `getRegionCodeForNumber(PhoneNumber)` - `getRegionCodeForCountryCode(int)` already returns `"ZZ"` when no region code is found. `UNKNOWN_REGION` as a constant is internal to the library.

It would be backwards-incompatible to make a change here, since clients are already checking for null rather than "ZZ" in the return value. More importantly, the behavior would change without alerting most clients (unless were testing library implementation which they shouldn't have to), since existing code wouldn't break, just do something differently, silently. Without a compelling reason such a change it's not worth the risk of breaking the contract of our public API so we can't do it at this time.

I think though that the difference between `getRegionCodeForNumber(PhoneNumber)` and `getRegionCodeForCountryCode(int)` could make sense. A `PhoneNumber` without a calling code which we can map is actually corrupt data and was not parsed by the library (or it is outdated data which the library can no longer work with). Whereas a calling code not in our metadata could be valid (such as +383, see https://github.com/googlei18n/libphonenumber/issues/1486). So the two kinds of parameters do not have the same restrictions.
