### ISSUE TITLE
International vs National

### ISSUE THREAD

**Issue by kennybuc** [googlei18n/libphonenumber#1972]
I've got a problem.
I'm going to create a validating function in app. Users can input the phone number either in full international phone number format or national number format.

Followings are possible cases.
1. +1 914 302 □□□□
2.   914 302 □□□□
3. +30699704□□□□
4.  699704□□□□

For the cases I mentioned above, I need the function to determine whether the phone number is international or local. 

While I'm using the twillio api, I need to send international number to the api.
When user just input the local (national) number, I can get country code based on user's location and therefore can generate international number. When user input international number, I can send it without any modification.
The problem is that I can't determine if user has input international number or local number.
Can you please help me with this problem?

Thanks!

**Comment by keghani** [comment]
Thanks for asking @kennybuc!

The Twilio API is not maintained in this repository. Maybe you want to ask them directly?

In our API, you can just sent the user input as-is, and we'll validate regardless of format. Try it on http://libphonenumber.appspot.com/

Could you confirm if you have an issue with our library? Otherwise let's close this and please ask Twilio. You're also welcome to ask non-issue questions to us or other users of the library at our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss).

**Comment by keghani** [comment]
I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
