### ISSUE TITLE
Indonesian Phone Numbers have an additional 62 appended in E164 Format

### ISSUE THREAD

**Issue by dlee423** [googlei18n/libphonenumber#1995]
Using the format noted here: https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue
* Country: ID
We have found that Indonesian numbers can be formatted with an additional 62 appended to the front, when using the E164 format. Indonesian numbers are in the format (62) xx - xxx - xxxx. This is happening when the area code and number without the 62 is 9 digits long. Having found these in previously reported issues, and we see that the prescribed solution is to either remove the additional 62 being appended or to prepend + when we know that the number is intended to a valid phone number.

There are currently no cases created for this issue here.

* Example number(s) and/or range(s):
* Number type ("fixed-line", "mobile", "short code", etc.):
Using an example of a mobile number, 6281181xxxx.
* For short codes, cost and dialing restrictions:
None.
* Where or whom did you get the number(s) from:
Internal client, but this applies to the general case.
* Authoritative evidence (e.g. national numbering plan, operator announcement):
Using the document which cited in PhoneNumberMetaData.xml: http://www.itu.int/oth/T0202000064/en
This is originating from the determination of "is this a national number" which is performed by using (L10286 in v8.8.5 of https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml).
<nationalNumberPattern>
	          (?:
	            [1-79]\d{6,10}|
	            8\d{7,11}
	          )
	        </nationalNumberPattern>

This number correctly is determined to be a national number by the above regular expression as it matches [1-79]\d{6,10}. This conforms to the document.
The normalized version 6281181xxxx is also determined (incorrectly) to be a national number. The relevant expression is: 49[0-37]\d\d{2,8}. Since this number starts with 62, [1-79]\d{6,10} matches, as well as the remainder the remainder 1181xxxx. Subsequently, this number is later prepended with the country code 62 for the E164 format thus making the number 62621181xxxx. The Indonesian number document notes that all area codes with 62 have a maximum range of 10 digits for numbers after the 62. Should the relevant regular expression to match national numbers that start with 62?
* Link from demo (http://libphonenumber.appspot.com) showing error:
http://libphonenumber.appspot.com/phonenumberparser?number=62811817028&country=ID http://libphonenumber.appspot.com/phonenumberparser?number=62816189636&country=ID

**Comment by penmetsaa** [comment]
@ dlee423,
Thank you for taking the time to improve libphonenumber!

8 to 11 digit 62X phone numbers are considered as valid fixed-line numbers in Indonesia. See: https://libphonenumber.appspot.com/phonenumberparser?number=62811817028&country=ID
Do you say that this is not right?

Note: The additional "+62" is added in E.164 format as the first 62 here is recognized as area code.

If you would like to consider first 62 to be recognized as country code, number need to be prefixed with "+" (as per E.164 formating). This way 811817028 is considered as valid mobile number. See: https://libphonenumber.appspot.com/phonenumberparser?number=%2B62811817028

To check the latest behavior for yourself, see our demo at https://libphonenumber.appspot.com

**Comment by dlee423** [comment]
@penmetsaa Thank you for the response.

Yes, I agree that 8 to 11 digit 62X phone numbers are considered valid fixed-line number in Indonesia. The issue that I am trying to bring up is that for numbers that abide to the 8 to 11 digit 62X phone numbers have an additional 62 added to the E.164 format. 

So are you saying the only fix for this would be to add the + in front of the 8 to 11 digit 62X phone number? Because with the example that you showed +6262811817028 is not a valid Indonesian number

**Comment by kkeshava** [comment]
@ dlee423,
In some cases, the library cannot tell if the leading digits of a phone number are intended to be the country calling code, or the start of the national significant number. Here ‘62’ is both a country calling code and an area code in Indonesia, so it is always better to add ‘+’ in front of the phone number to differentiate. This is actually addressed in our documentation: [Why wasn't the country code removed when parsing?](https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-wasnt-the-country-code-removed-when-parsing)

The number given by you +62 62811817028 is valid because as mentioned earlier 8 to 11 digit 62X numbers are considered valid in Indonesia.  Please see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=%2B6262811817028). Another way of checking the validity of the number is by adding national prefix ‘0’ in front of the number i.e ‘062811817028’  and ‘country code = ID’ . Please see [demo](http://libphonenumber.appspot.com/phonenumberparser?number=062811817028&country=ID)

Earlier we updated our library with 8 to 9 digit 62X numbers based on ITU Doc and later we increased it to 8 to 11 digit based on https://www.telkom.co.id (but we are unable to open the page which lists the area codes now). We would like to know if you can share / are aware of any newer numbering plan as the ITU doc is old and states it is max 9 digits only. We tried searching for online working numbers as well but we could not connect to any of them. If we do not find any official evidence or working numbers we might have to invalidate 11 digit numbers.

**Comment by kkeshava** [comment]
This issue is blocked on your or other GitHub contributors' input. Please help us find any newer numbering plan so that we can invalidate 11 digit 62 range. Otherwise we don't have enough information to fix the issue and may have to close it as infeasible.

**Comment by dlee423** [comment]
I just used the + sign as mentioned above. Thank you for the help!
