### ISSUE TITLE
US national format

### ISSUE THREAD

**Issue by jofournier** [googlei18n/libphonenumber#1996]
I've been looking at multiple sources regarding the US and CA telephone formats, (NANP, government agencies, the AP). The general consensus and practice points to the removal of the parentheses around the area code, in favor of using dashes in 10-digits number:  XXX-XXX-XXXX 
Parentheses meant the enclosed area code numbers were optional for dialing - which comes from a 7-digits dialing era. With 10-digits dialing being the widest enforced dialing method across US and Canada, parentheses around area code are little relevant anymore for representing a telephone number. Is this something that is on the radar for an update on the US/CA national formats in Google's libphonenumber to be more at parity with current dialing patterns?

**Comment by penmetsaa** [comment]
@jofournier, 
Thank you for taking the time to improve libphonenumber!

As the local number dialling is still possible (i.e just by entering the subscriber number without area code), we format number in (XXX) XXX-XXXX format when asked for national format. Once NANPA announced that only 10 digit dialling is possible, we would like to update the national format.

There's a silent majority who are fine with the current formatting, who prefer it even over something else. Thus we need overwhelming evidence when making a change, especially for such a prominent case such as national formatting for US/CA mobile/fixed-line numbers. We'd probably need to survey many stakeholders in this case.

Library formats the number in 10 digit format (i.e XXX-XXX-XXXX) if you try to format in E.164 way. See 
https://libphonenumber.appspot.com/phonenumberparser?number=%2B12012012345
This is because area code can not be skipped when dialling in E.164 format.
May be you can format your number in this way for your use case.

Since we can't find overwhelming evidence either, we are closing this issue, but please reopen if you're able to find an official source as per our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by penmetsaa** [comment]
Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.

**Comment by mizuni** [comment]
Hi @jofournier 

Sorry for the wait, and thanks so much for the additional research! We took some time to read into these sources and weigh options of moving from parentheses to hyphens. It's such a large market and potential impact to all the library users and stakeholders. We saw that some of the sources said both are possible, some were more passive recommendations, and many sources are not from telco regulators, but rather literary sources. 

Since it's there is no silver bullet (e.g. an announcement from a regulatory requesting a forced transition) or popular support for the change yet, we'll stick with the the status quo for now. This will avoid potentially having to roll back the change due to library users who prefer parentheses.

Thanks again for taking the time to report this with sources. It actually inspired us to update our FAQ on the topic for now: https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#when-does-formatting-in-a-country-change

Cheers,

The libphonenumber team

**Comment by jofournier** [comment]
Thanks for the update!
I believe it would be beneficial to offer both hyphen and parentheses formats, to reflect a wider range and more up-to-date 10-digits notational scenario (any/all numbers exposed to a national audience, displaying numbers in a web/delocated context where there is little chance a 7-digits dialing is relevant/possible, accounting for the fact that numbers and area codes are delocalized).  I believe the libphonenumber should not limit the communicaty to the past parentheses format presentation, perpetuating a format on mere community preference, but represent the latest correct formats that should be used. As far as rececommendations, I don't think the government and NANP's recommended format as XXX-XXX-XXXX are passive directives, but are in fact authoritative enough in that case, as well as Associated Press and Chicago Manual of Style, which are also authorities on the correct and acceptable formatting practices (not merely a "literary" sources) which have dropped the parentheses many years ago.  Please note that the official north american format for a telephone number is in fact 10-digits, seperated by hyphens, not parentheses.

I would recommend there is an available 10 digits hyphenated format to make sure we map to adequate formatting (at least for those who are willing to go beyond their own beliefs of what a phone number looks like, and follow the adequate notation of actual and factual dialing requirements).

**Comment by mizuni** [comment]
Thanks for the detailed response! Right now two formats isn't something we can prioritize as valid range updates are the priority for us to ensure the data is fresh and not blocking users.

Please consider joining the [discussion
group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further in order to get more input and a sense of impact.
