### ISSUE TITLE
Need to support new area codes

### ISSUE THREAD

**Issue by hfm-android** [googlei18n/libphonenumber#2001]
There are some new area codes in Iran. These numbers are related to mobile virtual network. 
samantel :
**099998**
**099999**
**0991**
**0992**
**0994**
**0995**
**0996**
**0997** 
Apptel:
**09991**
Parsian hamrahe lotous
**09990**
AzarTel:
**099914**

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

We can't find official evidence for the ranges 0991, 0992, 0994, 0995, 0996 and 0997.

We need more information to fix this. Please see our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by hfm-android** [comment]
@SumathiSundara You're right. I made a mistake. I didn't find official evidence for all prefix numbers, but I reform my comment and write some of them with related links below. thank you.

Country: Iran
Mobile prefix numbers :

0990 :
 It is a mobile number prefix for MCI prepaid sim card type and a special sim card for students.
https://www.mci.ir/new-number-0990
https://www.mci.ir/en/web/business/student-sim-cards

Mobile virtual network operator :

099998 and  099999 :
https://www.samantel.ir/en/

09991 :
https://www.aptel.ir/

09990 :
http://phlco.ir/

099914 : 
http://www.azartel.ir/

**Comment by SumathiSundara** [comment]
Thank you for continuing to take the time and effort to identify a source
online! This source you've provided is still insufficient as it's not a formal
authoritative source such as a numbering plan.

Since we can't find evidence either, we are closing this issue, but please
reopen if you're able to find an official source as per our [contribution guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md).

**Comment by hfm-android** [comment]
@SumathiSundara Finally, I found an Official evidence. I don't have privilege to reopen it. I'll open a new issue.
