### ISSUE TITLE
Leading zero gets truncated in E164 for some German numbers

### ISSUE THREAD

**Issue by nogoegst** [googlei18n/libphonenumber#2026]
*   Country: Germany
*   Example number(s) and/or range(s): +49016000000001
*   Number type: mobile (M2M)
*   Where or whom did you get the number(s) from: I used to own such a number.
*   Authoritative evidence (e.g. national numbering plan, operator announcement):

[Numbering plan for the numbering space for public telecommunications](https://www.bundesnetzagentur.de/SharedDocs/Downloads/EN/Areas/Telecommunications/Companies/NumberManagement/numbering_space/NP_numbering_space_2016.pdf?__blob=publicationFile&v=1)

> A zero in brackets means that the zero is not part of the number but must be dialled before the number when calling from a line in Germany. When calling from another country the international prefix applicable in the country (frequently "00" as in Germany) and the country code for Germany (written as "+49") must be dialled instead of the zero.

*   Link from demo (http://libphonenumber.appspot.com) showing error: E.164 does not have leading zero.

**Comment by penmetsaa** [comment]
@nogoegst,
Thank you for taking the time to improve libphonenumber!

>> When calling from another country the international prefix applicable in the country (frequently "00" as in Germany) and the country code for Germany (written as "+49") must be dialled instead of the zero.

As per section you are pointing to in the doc, the E.164 format should have +49 instead of 0. See the demo results are in line with that. See : https://libphonenumber.appspot.com/phonenumberparser?number=%2B49016000000001

When parsing the input number (i.e +49016000000001), 0 is trimmed off in order to successfully parse the number as in goo number of  cases the numbers are represented (like in online pages) in format +49 (0) 16000000001. This is to convey to users that national prefix 0 can also be used instead of country code when dialing within the country.

I'll close this as it's not an issue with the library. Please consider joining the [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) if you'd like to discuss this further.
