### ISSUE TITLE
Longer NZ Mobile Failing Validation despite being valid

### ISSUE THREAD

**Issue by Mitchies1970** [googlei18n/libphonenumber#2062]
NZ now allows 7 or 8 digits after the network code.

The library is failing the validation when 8 chars after the network code.

See below for example number that fails:

Fails (but is valid - see here: http://www.tnzi.com/numbering-plan)
+642123456789

**Comment by penmetsaa** [comment]
Thanks for providing all the details we need! We've accepted this issue;
however, we are now in a release freeze period and won't be releasing this
before third week of January.

For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](http://issuetracker.google.com/issues/new?component=192347), which we're currently testing.

Please note that you have submitted this information with the knowledge that we
may use, modify, reproduce, publicly display, and distribute the information in
accordance with our open source policies. Please let us know if you did not
intend to submit the information for such use.

**Comment by penmetsaa** [comment]
This will be fixed in the next release.

Join our [discussion group](https://groups.google.com/forum/#!forum/libphonenumber-discuss) to be notified of the Maven release's completion, or watch the GitHub repository at https://github.com/googlei18n/libphonenumber to be notified when we publish
the new release notes there.
