### ISSUE TITLE
Toll free french number with wrong local format

### ISSUE THREAD

**Issue by Nono31** [googlei18n/libphonenumber#2105]
Hello,
In accordance with the french [government website](https://www.economie.gouv.fr/particuliers/tarifs-numeros-commencant-par-08) and [infosva](http://www.infosva.org/#signaletique) the toll free and shared cost numbers are with the wrong local format
The number "0 800 12 34 56" should be "0 800 123 456"

**Comment by SumathiSundara** [comment]
Thank you for taking the time to improve libphonenumber!

There is conflicting evidence due to this other source we found online: https://en.wikipedia.org/wiki/Telephone_numbers_in_France.

The google search shows 52,90,00,000 for format 80x xx xx xx & only 52,70,00,000 for format 80x xxx xxx. The numbers shown are seems to be example number but not regarding formats.

We'll do more research to confirm. However, metadata updates are the priority for us to ensure the data is fresh. We will get to this as soon as we have some free time.

**Comment by kkeshava** [comment]
I'm closing as this issue is infeasible for us to fix at this point (we need more information). For your next metadata issue, we invite you to file issues in Google's new [Issue Tracker](https://b.corp.google.com/issues/new?component=192347), which we're currently testing. if you respond so we pick up on it.
