### ISSUE TITLE
Argentina - Invalid Format for Mobile Area Codes 387 and 388

### ISSUE THREAD

**Issue by mihaelacr-google** [googlei18n/libphonenumber#559]
Imported from [Google Code issue #559](https://code.google.com/p/libphonenumber/issues/detail?id=559) created by [martindaloia](https://code.google.com/u/110327941144057018648/) on 2014-11-19T20:40:02.000Z:

----
Given this valid E.164 mobile number: +54 9 387 684 1111 (the last part was modified to preserve the identity)
Current National Format: 03876 15-84-8695
Expected National Format: 0387 15-684-8695

Given this valid E.164 mobile number: +54 9 388 570 1111 (the last part was modified to preserve the identity)
Current National Format: 03885 15-70-1111
Expected National Format: 0388 15-570-1111

Version used: 7.0.0

This information is taken from the Argentinian bureau of communications called CNC. You can download this Excel where are all the assigned Area Codes (column INDICATIVO) and the Prefix number (column BLOQUE, which in this case are 684 and 570 respectively):

http://www.cnc.gob.ar/multimedia/noticias/archivos/201411/archivo_20141118022303_914.zip
(The link was obtained from this URL: http://www.cnc.gob.ar/asignaciones-a-la-fecha_p445 (On the right side there is a link with a &quot;Númeración Geográfica&quot; as a label))

You can filter INDICATIVO by 387 and 388, and BLOQUE by 570 and 684 to see all of them.

=======

Below there is a Workaround that we made in the PhoneNumberMetadata.xml to change this behavior but we are not sure that doesn't affect other formats:

We modified these 2 lines (883 and 884): https://code.google.com/p/libphonenumber/source/browse/trunk/resources/PhoneNumberMetadata.xml?r=715#&nbsp;883
and changed like this:

[...]

  8(?:
    [01]|
    3[013469]|
    5[0-39]|
    7[0-24-69]|
    8[0-59]
  )

[...]

**Comment by mdaloia** [comment]
The link to the file on `code.google.com` is not accessible anymore.

The equivalent to `github.com` is:
https://github.com/googlei18n/libphonenumber/blob/b5e59c4e803739422bbcfbd1b8fdf29ffd25eec4/resources/PhoneNumberMetadata.xml#L883

**Comment by hagbard** [comment]
Thanks for the bug report and details. I looked at the spreadsheet data and there are some issues:

In the 387 range, the 4 digit area codes end in 3,6,7,8
In the 387 range, the 3 digit area codes end in 4,5,6

In the 388 range, the 4 digit area codes end in 5,6,7,8
In the 388 range, the 3 digit area codes end in 4,5,6

This means that the following contradictions exist:
"3876 XX" (x 10) vs "387 6XX" (x 22)
"3885 XX" (x 1) vs "388 5XX" (x 58)
"3886 XX" (x 11) vs "388 6XX" (x 3)

My proposal would be to change the following into 3-digit area codes:
3874, 3875, 3876
3884, 3885

But not (yet) 3886 as there are more case where it's used as a 4 digit area code.

Unfortunately the patch you provided won't work because the "leading digits" patterns must much a precise number of digits. The second pattern must match exactly 4 digits in all paths and you have changed it so it matches 5 digits in some cases. For performance and maintenance reasons we only differentiate down to 4 digits in the leading digits, so the contradictory cases above will have to remain incorrect for some cases (ie, "3876 XX", "3885 XX" and "388 6XX").

If you think this is unacceptable, please let us know (we might be able to make an exception, but we'll have to weigh up the pros and cons carefully).

Now I have the XLS spread-sheet I can also look at other area codes and check our data.
Thanks again.

**Comment by hagbard** [comment]
Unfortunately the prefix 3876 appears in the XSL document as _both_ a 3 digit area code and a 4 digit area code. The 4 digit area code appears twice as often as the 3 digit one:
387 6XX XXXX		56 times
3876 XX XXXX		99 times

Similarly 3885 also appears as both 3 and 4 digit codes:
388 5XX XXXX		120 times
3885 XX XXXX		45 times
Here the 3 digit version is more common.

As we are only currently looking at a maximum of 4 digits to determine the formatting, the best we can do is say that 3876 is a 4 digit area code and 3885 is a 3 digit area code.
