### ISSUE TITLE
Canadian carrier data not supported?

### ISSUE THREAD

**Issue by DevMomo** [googlei18n/libphonenumber#596]
I've parsed multiple Canadian phone numbers and carrier info always seems to be blank. Looking at `resources/carrier/en/1.txt` I can't find any metadata on Canadian numbers either.

Canadian mobile network code identifiers can be found [here](http://en.wikipedia.org/wiki/Mobile_country_code#C) and [here](http://www.cnac.ca/other_codes/imsi/imsi_codes.htm).

Any way to add support for these? And any way I can contribute if this is feasible?

**Comment by dlyongemallo** [comment]
Are you asking about supporting the MCC and/or MNC, or do you have information about the prefixes used by carriers? The links you cited don't have this carrier information.

**Comment by DevMomo** [comment]
What does this library need to support Canadian phone number carrier info?

In a way I'm asking if MCC/MNC is viable, and why Canadian prefixes aren't currently available.

**Comment by dlyongemallo** [comment]
I don't understand what you mean by whether the MCC/MNC is viable. There is no relationship that we know of between the MCC/MNC and the carrier prefix. A mobile carrier may happen to use a prefix that is the same as its MCC or MNC, but when this happens it's just a coincidence.

Canadian mobile numbers are assigned geographically, by where the number was originally registered. Canada also has wireless number portability (http://www.crtc.gc.ca/eng/info_sht/t1025.htm), which means that you can keep your mobile number if you move elsewhere, or switch carriers. 

For example, 250 is the MNC for ALO. It's also the geographic prefix for Vancouver Island. A person with a number beginning "+1 250..." got her number while on Vancouver Island. She may later move elsewhere, and take that number with her. She can also switch carriers. If her carrier happens to be ALO, then her mobile prefix will be the same as the carrier's MNC. But in the general case, this won't be true.

So, as far as I can tell, it's not possible to determine the carrier from a phone number's prefix. If you have information otherwise, we'd be happy to add it.

**Comment by DevMomo** [comment]
Makes me wonder how lookup services such as [Data 24-7's](http://www.freecarrierlookup.com/) can take into account number portability and detect carrier changes. I'm still learning however.

Thank you very much for the feedback. I'll let you know if I have anything.

**Comment by dlyongemallo** [comment]
I don't know, but they probably just have a database listing the carrier for every number, which they pay to maintain. That's really the only way they can support phone number portability.
