### ISSUE TITLE
Add Android example to README.md

### ISSUE THREAD

**Issue by vrunoa** [googlei18n/libphonenumber#597]
Hey guys, I just add a quick android example to use libphonenumber with TextWatcher, let me know if this is OK to create a PR. 

[https://github.com/Urucas/libphonenumber/blob/master/README.md](https://github.com/Urucas/libphonenumber/blob/master/README.md)

**Comment by ritunagpal** [comment]
I am not getting how to add libsphonenumber as library in my android project.
I have downloaded the jar from here
http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/
and add as a library in my project.
But no use.
I am not able to use PhoneUtils class.

**Comment by keghani** [comment]
Thanks @vrunoa! Sorry it took us so long to see this.
We probably don't want to include that code snippet in our README since it's specific to your setup and we can't own support or debugging if anyone tries to use it and has questions. We can still refer our users to it. Thanks for using libphonenumber and being helpful to our community!

@ritunagpal Please file new issues separately for quicker responses and so everyone gets to see and offer to help - some contributors may have muted this thread. I filed https://github.com/googlei18n/libphonenumber/issues/1113

**Comment by juliecain** [comment]
#1209 #1209
