### ISSUE TITLE
Invalid country calling code for US Minor Island

### ISSUE THREAD

**Issue by lazaa** [googlei18n/libphonenumber#599]
I get "Invalid country calling code" when I use UM as country code. It is a 3166-1 code (though it is redundant and has a US-UM 3166-2 code as well):
https://www.iso.org/obp/ui/#iso:code:3166:UM

However, the phone number format should be the same as US or CA, i.e. +1 XXX-XXX-XXXX.

I have tried multiple numbers (e.g: 215-123-4567) but with no luck. I could parse the number with US or CA country code but not with UM. Please fix.

**Comment by andyst** [comment]
@jias0001 is there a precedent for this?

 - There's no metadata for "UM". Users have a workaround (e.g. selecting "US" or specifying the number with +1). Developers have a workaround, e.g. not listing "UM" as available region.
 - Do we generally add metadata for such cases or don't we?
 - To support "UM" as selectable region, would we have to copy the complete "US" metadata to support "UM" as a country code? Or is there an data aliasing / inheritance way of doing this? Or would a very bare-bones "UM" config do it?

**Comment by dlyongemallo** [comment]
The phone number library supports the list of countries listed by the ITU:
http://www.itu.int/oth/T0202.aspx?parent=T0202

In the case of the U.S. Minor Outlying Islands, the correct region code to use would be "US", since their telephone numbers are administered by the United States as far as the ITU is concerned. 

@lazaa - Do you have a specific reason why you need to use the code "UM"? It's just a convenience designation for a series of islands with nothing much in common other than being under US sovereignty, and no permanent population.

**Comment by lazaa** [comment]
@dlyongemallo - the only reason for using UM is that we are leveraging a wide list of ISO codes as the country code part of the address (we extended the list from java Locale with few obsolete codes). I tried to use that as the default country but I have found other codes as well that I cannot expect to work in this api. So I have created a mapping in my wrapper.

This is my mapping:
		map.put("AN", "BQ");
		map.put("AQ", "NF");
		map.put("BU", "MM");
		map.put("BV", "NO");
		map.put("CS", "RS");
		map.put("GS", "FK");
		map.put("HM", "NF");
		map.put("PN", "NZ");
		map.put("TF", "MQ");
		map.put("TP", "TL");
		map.put("UM", "US");
		map.put("YU", "HR");

Thanks for taking time to respond my complaint. I'm really thankful for having this api around.
