### ISSUE TITLE
French Phone Number is considered as valid when it is not the case 

### ISSUE THREAD

**Issue by juandbarraza24** [googlei18n/libphonenumber#662]
The following number is considerd as a valid phone number for FRANCE +33600000000. 
On the other hand, The algorithm works fine when the the phone number 	+33700000000. (Phone is considered as invalid).

Thanks,

Juan

**Comment by keghani** [comment]
Thanks for filing this issue juandbarraza24. The short answer is that this doesn't require a fix.

Because we use prefixes and regular expressions to determine phone number validity, there will be some ranges that we consider valid in which some specific numbers are invalid. In this example, the +336xxxxxxxx range is valid, but we don't nitpick on which exact numbers in there have actual use.

We want to make sure that any actual numbers are considered valid by the library; if you encounter such numbers that are considered invalid please raise an issue. On the other hand, we're more lenient towards numbers that are wrongly considered valid.
