### ISSUE TITLE
43 is not supportted

### ISSUE THREAD

**Issue by ahmetkarakaya** [googlei18n/libphonenumber#666]
Although the following MSISDN is valid, I am getting notvalid number error. When I change the MSIDN number by adding "00" as prefix  like "00436642161003" it works fine,
Although for other countries such as 90, 1 ,49 I can pass MSISDN number without 00 prefix and it works properly, Why I need to add 00 for the country 43.

Howver when I have appied same logic (adding "00" as prefix) for the USA number I am gettibg invalid number. So my workaround solution is not properway

      // Check msisdn valid?
      PhoneNumberUtil phoneUtil = PhoneNumberUtil.getInstance();
      PhoneNumber number = null;
                        
      String msisndn = "436642161003";
      String region = "AT";

      System.out.println(phoneUtil.getCountryCodeForRegion(region));
      try {
         number = phoneUtil.parse(msisndn, region);
      } catch (NumberParseException e) {
         e.printStackTrace();
      }

      System.out.println("RegionCode valid:" + phoneUtil.isValidNumber(number));

**Comment by roes** [comment]
Hi,
We parse numbers in national or international format, so either you need to format the number in national format (without the country code) and supplying the region, or you need to format it in international format, for this you need to either add the international prefix or '+' in front of the country code.
For your example to parse properly you either need to call with:
msisndn = 6642161003 (national format) or
msisndn = +436642161003 (international format, works for all countries) or
msisndn = 00436642161003 (international format, works if region = Austria)

"436642161003" doesn't work because we interpret it as a national number, and for this example it isn't valid. For other countries, numbers starting with the same digits as the calling code might be valid, which is why it works in some cases (however, it won't be the number you expected, if your example passed it would be the number +43 43664...).

"00" isn't the international prefix for US, "011" is, therefore appending "00" wouldn't work if region = US

The easiest way to get it to work is appending '+' if you know it's in msisdn format.

**Comment by ahmetkarakaya** [comment]
I have added + at the beginning of MSISND, and tested two cases, here is the results and what I was expecting..
    
String msisndn = "+178095257XX";
    String region = "US";
phoneUtil.isValidNumberForRegion(number,region));  return false;   // I am expecting it returns true,
phoneUtil.isValidNumber(number)  return true;

 String msisndn = "+178095257XX";
      String region = "TR";

phoneUtil.isValidNumberForRegion(number,region));  return false;
phoneUtil.isValidNumber(number)  return true;   // I am expecting it returns false,

**Comment by roes** [comment]
Hi,
The reason the number is not valid for region US is that it's a Canadian number, not a US one.

And I'm not sure why you're expecting the two equal calls to isValidNumber(number) to return different things?

You can use our demo to try numbers out: http://libphonenumber.appspot.com/

**Comment by ahmetkarakaya** [comment]
Thanks, sorry it was my fault. I want to know somethinf else

How ofter your library updated once new operator comes in live.

**Comment by roes** [comment]
Our library is updated continuously, we are however dependent on getting good information. We try to address bug reports within a week, if you create a pull request yourself it might go in quicker.
The jar (and binary data files) is released once or twice a month, but you can build them yourself.

For questions rather than bug reports please use our mailing list libphonenumber-discuss@googlegroups.com (https://groups.google.com/forum/#!forum/libphonenumber-discuss)
