### ISSUE TITLE
PhoneNumberToCarrierMapper not included in libphonenumber-7.0.4.jar

### ISSUE THREAD

**Issue by rgurley** [googlei18n/libphonenumber#670]
The class and the carrier data is not available in the jar downloaded here:

http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/7.0.4/libphonenumber-7.0.4.jar

**Comment by rgurley** [comment]
Nor is the geocoder

**Comment by andyst** [comment]
Thanks for the notice!

I think there's an issue with our new release process. The latest carrier release was with libphonenumber 7.0.2 at http://repo1.maven.org/maven2/com/googlecode/libphonenumber/carrier/1.9/ (January 19th).

The latest geocoder release dates back to 2014.

For now, please either build your own carrier.jar from the sources at https://github.com/googlei18n/libphonenumber/tree/master/java/carrier or you can get the January version of the .jar from the link mentioned above.

We'll look into fixing the release process.

**Comment by roes** [comment]
Hi,
The carrier and geocoder have their own jars, which is why you can't find them in the libphonenumber.jar

Unfortunately the sorting for the jars is a bit unintuitive, but the latest ones are there;
Carrier http://repo1.maven.org/maven2/com/googlecode/libphonenumber/carrier/1.10/
Geocoder http://repo1.maven.org/maven2/com/googlecode/libphonenumber/geocoder/2.20/

**Comment by andyst** [comment]
D'oh, roes@ is right. It's all there, it's working as intended.

**Comment by rgurley** [comment]
Oh, I see. I should have tried going up one in the URL. The readme.md specified http://repo1.maven.org/maven2/com/googlecode/libphonenumber/libphonenumber/ and I didn't think to look elsewhere. Thanks for the tip! :)

**Comment by duranmla** [comment]
:100: You guys should drop this into the README.md thanks for this issue! 👍
