### ISSUE TITLE
Difference between Java + JavaScript version in parseAndKeepRawInput

### ISSUE THREAD

**Issue by giggsey** [googlei18n/libphonenumber#672]
Looking at `parseAndKeepRawInput`, it seems that the JavaScript version will try to work out the country code if the one supplied is not valid ([phonenumberutil.js](https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumberutil.js#L3713-3717)), whereas the Java version doesn't seem to do the same ([PhoneNumberUtil.java](https://github.com/googlei18n/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L2795)).

Should the Java version be trying to auto-detect the country code?

(Related to giggsey/libphonenumber-for-php#61)

**Comment by lutzissler** [comment]
I’d like to add that [lines 3713–3717](https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumberutil.js#L3713-3717) look like they’re not necessary anyways as:

- [lines 3792–3795](https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumberutil.js#L3792-L3795) will check for either a valid default region or a + sign and throw an `INVALID_COUNTRY_CODE` in case neither is present, and
- [line 1013](https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumberutil.js#L1013) will check for an empty string when checking if the string could be a valid number, and [line L3787](https://github.com/googlei18n/libphonenumber/blob/master/javascript/i18n/phonenumbers/phonenumberutil.js#L3787) will throw a `NOT_A_NUMBER` exception if it’s not.

**Comment by andyst** [comment]
Sorry, I see this issue didn't get a response from the team.

Regarding @giggsey's report, can you write JS & Java unit tests which show the difference in behavior between JS and Java? (E.g. as a Pull Request which we won't submit but which illustrates the issue.)

I just looked at the code and can't see the difference. Maybe the issue got fixed within the last (almost) 3 years since it was filed?

I'll mark this as closed. Because we're migrating to a new issue tracker, please continue the discussion (if you still care, again, sorry about the non-response so far) by creating a Pull Request or by filing an issue in our new issue tracker at https://issuetracker.google.com/issues/new?component=192347

Thank you!
