### ISSUE TITLE
Argentina - Mobile numbers reported as landline

### ISSUE THREAD

**Issue by jojoman2** [googlei18n/libphonenumber#684]
Argentinian mobile numbers like 116907XXXX are reported as landine by the function getNumberType. If you insert 15 after 11 it is correctly reported as a mobile number. The 15 is necessary when calling a mobile phone from a landline phone but when calling from another mobile phone it is not. See more information here: http://en.wikipedia.org/wiki/Telephone_numbers_in_Argentina#Mobile_phone_numbers
In Argentina, like in many parts of the world, people are almost always using mobile phones so they often omit the 15. If it is hard to tell whether a number like the above is landline or mobile, maybe it could return FIXED_LINE_OR_MOBILE?

**Comment by hagbard** [comment]
Is this a question about the specific range 116907XXXX, or fixed line numbers in general ?

**Comment by jojoman2** [comment]
Mobile numbers written without a 15 in general

**Comment by ruimarinho** [comment]
It also looks like if number 9 is prepended, the phone number is also the same.

E.g. `+54 11 XXXX XXXX`  ==  `+54 9 11 XXXX XXXX` (11 23456789 / 9 11 23456789). Currently, libphonenumber reports the first number as MOBILE and the second one as FIXED_LINE, which is not the case.

**Comment by ruimarinho** [comment]
Any chance of looking at this @hagbard?

**Comment by drzraf** [comment]
Tell me if I'm wrong, but (011) 6907XXXX could be as well a land-line phone number (if called from land-line)
I also have some double about this [line](https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L786):
``nationalPrefixTransformRule="9$1" nationalPrefixFormattingRule="$NP$FG"```
The "9" prefix when using i18n notation is only for mobile phone. For land-line numbers the prefix is "1"

**Comment by penmetsaa** [comment]
@jojoman2 and @ruimarinho,

Sorry for the delay in response.

There is no sufficient numbering allocation plan that we can refer for Argentina yet in order to identify (and solve) the overlapping of mobile and fixed line numbers due to different formats as @drzraf points out. Please share any official evidence you may have. See our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence). Please feel free to reopen this bug if detailed official numbering plan (with mobile vs landline range details) is available.

To further complicate matters, the mobile token is 9 internally, but 15 domestically - although neither are used for SMS or fixed line interactions. As for fixed lines, lengths and ranges differ depending on the province, which may overlap with mobile number formats.

The only way to categorize mobile numbers is whether the input have indicator digits like 15 or 9. Libphonenumber can not do anything better with limited numbering plan details available and complexity in reaching the numbers as mentioned above.


@drzraf,
Regarding ```nationalPrefixTransformRule``` 

If mobile token 15 is present in the input, it will be trimmed off and mobile token 9 is placed before the area code in case E.164 format is asked. Ex: https://libphonenumber.appspot.com/phonenumberparser?number=0+223+15+123-4567&country=AR
More details mentioned above.
