### ISSUE TITLE
US phone numbers carrier mapper not returning carrier name

### ISSUE THREAD

**Issue by ranga543** [googlei18n/libphonenumber#726]
Carrier name is empty for US (United States of America) Phone Numbers.

Sample Code:

PhoneNumber swissMobileNumber =
			    new PhoneNumber().setCountryCode(01).setNationalNumber(740XXXXXXXL);
			PhoneNumberToCarrierMapper carrierMapper = PhoneNumberToCarrierMapper.getInstance();
			System.out.println(carrierMapper.getNameForNumber(swissMobileNumber, Locale.ENGLISH));

**Comment by dlyongemallo** [comment]
Can you please change the issue title to be more specific? The US phone carrier map is not empty:
https://github.com/dlyongemallo/libphonenumber/blob/master/resources/carrier/en/1.txt

It looks like you're reporting that the prefix 740 is missing from the carrier map. In that case, do you have any documentation about which carrier this is? And is any other range missing?

[I assume that your sample code says "swissMobileNumber" because you copied it from somewhere else, and that this issue has nothing to do with Swiss mobile numbers.]

**Comment by ranga543** [comment]
I copied the sample code from github but I did not change variable names and the carrier for that phone number is AT&T.

**Comment by dlyongemallo** [comment]
According to NANPA, 740 is a prefix for Ohio, US:
http://www.nanpa.com/enas/npa_query.do

Most American telephone prefixes are tied to geography rather than carrier, so that it's impossible to infer the carrier from the prefix. This is why they are classified as FIXED_LINE_OR_MOBILE. Unless you have information that the 740 prefix is served only by AT&T (this seems extremely unlikely), the library is working as intended.
