### ISSUE TITLE
Belarus mobile number ("life :)") AsYouTypeFormatter dont work

### ISSUE THREAD

**Issue by aimtechnology** [googlei18n/libphonenumber#732]
Tested here:
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
Number is: 375 25 765 43 21 (or 25 765 43 21),
where 375 - Belarus code, 25 - mobile operator "life :)" code and 765 43 21 - phone number.
Default country set to "BY"
```
****AsYouTypeFormatter Results****
Char entered: 3 Output: 3
Char entered: 7 Output: 37
Char entered: 5 Output: 375
Char entered: 2 Output: 3752
Char entered: 5 Output: 37525
Char entered: 7 Output: 375257
Char entered: 6 Output: 3752576
Char entered: 5 Output: 37525765
Char entered: 4 Output: 375257654
Char entered: 3 Output: 3752576543
Char entered: 2 Output: 37525765432
Char entered: 1 Output: 375257654321
```

**Comment by mihaelacr-google** [comment]
Hi,

Thanks for your report.
If you add a + to the number it will work. Try +375257654321 in the demo, and you will see it is formatted correctly. The number will be also formatted correctly if you enter it in national number format: 375 25 765 43 21.

The AsYouTypeFormatter has certain constraints due to its online nature (has to be very fast + make decisions "as you type", without having the complete number).
