### ISSUE TITLE
Germany mobile numbers not recognized as valid

### ISSUE THREAD

**Issue by Frintrop** [googlei18n/libphonenumber#747]
We have some verified germany mobile numbers which would not be validated successfull:

Example 01767056762 ( Mobile number, Provider O2/Telefonica )

We are new to libphonenumber and don´t know to adjust the metadata.

**Comment by roes** [comment]
Hi,
Do you have supporting evidence of the numbers being valid? For example official documentation from the government, telecom authority or carrier are good. If none of them are available, news reports of the introduction of the new prefixes are also OK.

**Comment by Frintrop** [comment]
Hi,

0176 numbers are still valid if they have 12 digits ( 017670567621), but numbers with 11 digits would marke das invalid. So it´s no new area code/prefix, only another format. We can check this numbers via  german online tools or a sms to o2/telefonica ….

Do you need still official documentation ?

Thx. André

Von: roes [mailto:notifications@github.com]
Gesendet: Freitag, 17. Juli 2015 11:39
An: googlei18n/libphonenumber
Cc: André Frintrop
Betreff: Re: [libphonenumber] Germany mobile numbers not recognized as valid (#747)


Hi,
Do you have supporting evidence of the numbers being valid? For example official documentation from the government, telecom authority or carrier are good. If none of them are available, news reports of the introduction of the new prefixes are also OK.

**Comment by roes** [comment]
Hi,
We need to something to know they're actually in use, is there a website for a business that has one of these numbers? Have you called one of them so you know they're actually dialable?

**Comment by Frintrop** [comment]
You can check this number with many online tools: http://www.pimp-app.com/abfrage/

geprüfte Nummer: 01767056762 (Mobil) 

    Original-Provider: o2
    Original-Netz: o2
    portiert: nein

We have some customers which can not register within our mobile token protected app having this number format. We have checked this numbers. They are callable and dialable ....

**Comment by keghani** [comment]
Hi,

I tried calling +491767056762 from Switzerland and it does not connect. The message is:
  "Die gewaehlte Verbindung kann nicht hergestellt werden."

Note that the online tool you linked to is not performing strict checks; it gives the same output for "01767".

Let's talk in E.164 format (including the country code, as above) instead of local format to remove ambiguities.
We really need evidence that this number or a number of this length starting with "0176" is valid before we support them. You said "We have some verified germany mobile numbers" - how was this verified? Can you share information about what carrier you dialed from, on what device (mobile, fixed line, ...), and the exact format of the number you dialed?

**Comment by Frintrop** [comment]
We are investigating …

**Comment by penmetsaa** [comment]
Hi,

Please confirm the updates if the investigation is done.

Thanks & Regards,
Aravind

**Comment by Frintrop** [comment]
This case was wrong. Waiting for next customer having this problem. Thx for  that

Von: penmetsaa [mailto:notifications@github.com]
Gesendet: Mittwoch, 5. August 2015 09:05
An: googlei18n/libphonenumber
Cc: André Frintrop
Betreff: Re: [libphonenumber] Germany mobile numbers not recognized as valid (#747)


Hi,

Please confirm the updates if the investigation is done.

Thanks & Regards,
Aravind

**Comment by keghani** [comment]
Thanks for clarifying! Closing this issue.
