### ISSUE TITLE
Brazilian mobile phone numbers need to update

### ISSUE THREAD

**Issue by renatofilho** [googlei18n/libphonenumber#773]
Since January 29, 2012 Brazil has being migrating the mobile phone numbers from 10 to 11 digits, the prefix 11 is working nice with libphonenumber, but recently some new regions get update and it still using older format on libphonenumber. 

For example; (81) 8704-2155 got update to (81) 98704-2155

Check http://www.howtocallabroad.com/forums/topic/brazil-telephone-numbering-changes for more details

**Comment by andyst** [comment]
+55 (81) 98704-2155 is considered valid by libphonenumber.

You can test +55 (81) 98704-2155 at https://libphonenumber.appspot.com/ .

Which version of libphonenumber are you using?


We've implemented all official changes (e.g. the ones scheduled for 2015-05-31) already.

The next change by Brazil is scheduled for 2015-10-11.
See:
http://www.itu.int/dms_pub/itu-t/oth/02/02/T020200001D0001PDFE.pdf

We'll implement / release those October changes in October.

Please reopen this issue if it turns out to be a problem that's still there in the latest version of libphonenumber. Thanks!

**Comment by renatofilho** [comment]
Thanks for the quick reply. 
Yes the problem was that I was using a old version. Updating to a new version fixed the problem.
