### ISSUE TITLE
Myanmar - new mobile prefix

### ISSUE THREAD

**Issue by alecx** [googlei18n/libphonenumber#778]
Ooredo MM started using 996 prefix. 

Documentation can be provided privately if required.

**Comment by andyst** [comment]
Thanks.
Documentation is always required. :)

The latest (and pretty new!) ITU doc doesn't mention it, does it?
http://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000920003PDFE.pdf

**Comment by alecx** [comment]
Looks like the ITU doc only has the state owned telco :) Let me know where to send the docs for all issues.

**Comment by roes** [comment]
Thank you for your report, we'll start working on this shortly.

**Comment by havardk** [comment]
Hi,

I'm adding to this bug since it concerns the same country.

+95926xxxxxxx has also been seen in the wild.  This series is in the lates ITU doc.

There are a few more series that are in the latest ITU doc that are not supported.  I don't know if these are actually used yet.  They are:
+95942xxxxxxx
+95930xxxxxx
+95932xxxxxx

**Comment by roes** [comment]
Thank you for letting us know, we are working on incorporating the latest ITU updates.

**Comment by keghani** [comment]
Fixed in release 7.0.11.
