### ISSUE TITLE
Format as you type works differently for different countries

### ISSUE THREAD

**Issue by buddyackerman** [googlei18n/libphonenumber#801]
Why does US format any set of numbers while other countries only format the number if it's a valid number.  For instance, ten 5's will format when the country is US but not when it's Germany.  Ten 5's is not a valid number in the US so why does the US number format but not he the German number?  Also, the US formatter will ignore numbers after ten digits are typed but other countries don't have the same functionality?

**Comment by dlyongemallo** [comment]
All formatting and validation rules are country-dependent. Formatting and validation are only tangentially related. For simplicity, the formatting rules are prefix-based and thus are made to apply to more than just valid numbers. In particular, prefixes of valid numbers will also have formatting applied to them (see the as-you-type-formatter for this in action).

I'm not sure why you think ten 5s is not valid or not formatted in Germany. It is:

Validation Results
Result from isPossibleNumber()	true
Result from isValidNumber()	true
Result from isValidNumberForRegion()	true
Phone Number region	DE
Result from getNumberType()	FIXED_LINE

Formatting Results
E164 format	+495555555555
Original format	5555 555555
National format	05555 555555
International format	+49 5555 555555

The reason that numbers longer than 10 digits are not valid in the US in the library is because, in fact, numbers longer than 10 digits are not valid in the US, whereas other countries (like Germany) have valid numbers which are longer.

You seem to be suggesting that the library is giving some sort of preferential treatment to the US. It is not. It's treating US numbers with rules which are appropriate to US numbers, and German numbers with rules which are appropriate to German numbers.

**Comment by buddyackerman** [comment]
I think the problem is in the AsYouTypeFormatter.  From your demo page (shown below) the format is correct but the AsYouTypeFormatter results are not formatted.  Why is there a difference between the "regular" formatter and the AYT formatter?


****Parsing Result:****
{"country_code":49,"national_number":5555555555,"raw_input":"5555555555","country_code_source":20,"preferred_domestic_carrier_code":""}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Result from isValidNumberForRegion(): true
Phone Number region: DE
Result from getNumberType(): FIXED_LINE

****Formatting Results:**** 
E164 format: +495555555555
Original format: 5555 555555
National format: 05555 555555
International format: +49 5555 555555
Out-of-country format from US: 011 49 5555 555555
Out-of-country format from Switzerland: 00 49 5555 555555

****AsYouTypeFormatter Results****
Char entered: 5 Output: 5
Char entered: 5 Output: 55
Char entered: 5 Output: 555
Char entered: 5 Output: 5555
Char entered: 5 Output: 55555
Char entered: 5 Output: 555555
Char entered: 5 Output: 5555555
Char entered: 5 Output: 55555555
Char entered: 5 Output: 555555555
Char entered: 5 Output: 5555555555
