### ISSUE TITLE
libPhoneNumber NoClassDefFound

### ISSUE THREAD

**Issue by mikebell90** [googlei18n/libphonenumber#896]
7.1.1 - fine
7.2.0 - exhiibits issue
Maven deployment

The issue appears to be the change referred to in https://groups.google.com/forum/#!topic/libphonenumber-discuss/NjjOxhnR4No

Error:
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.nano.MessageNano
com.google.i18n.phonenumbers.MultiFileMetadataSourceImpl.loadMetadataAndCloseInput(MultiFileMetadataSourceImpl.java:140)

Replication:
PhoneNumberUtil.getInstance().parse("+14157503937","US");

**Comment by mikebell90** [comment]
Maven dependency
<dependency>
			<groupId>com.googlecode.libphonenumber</groupId>
			<artifactId>libphonenumber</artifactId>
			<version>7.2.0</version>
		</dependency>

**Comment by mikebell90** [comment]
Did a little more investigation, think I know what's happening

- I use Java (server version)
- The new build uses protobufs, but not protobufs as defined in the pom, but protobuf "nano" version, which I'm not sure what the maven dependency declaration is?
- The pom marks the protobufs as preferentially loaded from a local jar. so googles tests passed

Is there going to be a resolution to this for non android folks?

**Comment by Hronom** [comment]
I have similar issue...

**Comment by keghani** [comment]
Thanks for reporting! 7.2.0 is a bad release, please don't use it. We're investigating.

**Comment by RobThree** [comment]
> Thanks for reporting! 7.2.0 is a bad release, please don't use it. We're investigating.

Crap :laughing: 
Just fixed it for my usecase :grin: 

What I figured out is that it (now) requires protobuf; as far as I could [see / find 2.6.1](https://github.com/googlei18n/libphonenumber/commit/7ee44b6e9126819aca92e2515441ec04e31ad56d) should suffice (got it from [here](https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/)) however, it turns out that 2.6.1 has no "nano" version (`MessageNano` missing for example). So I got [protobuf-javanano](https://repo1.maven.org/maven2/com/google/protobuf/nano/protobuf-javanano/), which is only available in alpha's, and tried that. That worked for me (but I do have a bit of a special scenario where I use IKVM.Net to "compile" the libphonenumber to a .Net .dll).

**Comment by keghani** [comment]
7.2.1 was pushed to Maven and may take a while to be available. It contains the fix.

Let us know if you face any issues. Thanks for your patience!
Keghani

**Comment by Stephan202** [comment]
@keghani: Thanks, can confirm that version 7.2.1 behaves as expected.

**Comment by RobThree** [comment]
@keghani Can also confirm that 7.2.1 behaves as pre-7.2.0 and as expected. Thanks!

**Comment by mikebell90** [comment]
Also confirmed.

**Comment by keghani** [comment]
Thanks for confirming everyone!

**Comment by venkyarya** [comment]
I see this issue with 7.2.6.

I have included com.google.protobuf 2.4.1 and com.googlecode.libphonenumber 7.2.6 in my web application, and i get NoClassDefFound error and my application fails to deploy.

**Comment by RobThree** [comment]
> I see this issue with 7.2.6.

I'm pretty sure 7.2.6 is okay?

**Comment by keghani** [comment]
@venkyarya that's probably because you have your own protobuf dependency. See #913.
For libphonenumber 7.2.1 and above you need a protobuf version with javanano. This isn't yet stable on Maven Central (and 2.4.1 does not have javanano). Try not including your own com.google.protobuf.

**Comment by venkyarya** [comment]
Thanks @keghani .
Including libphonenumber 7.2.6 and Not including protobuf did not help.

Since libphonenumber 7.2.6 had protobuf 2.6.1, replace protobug 2.4.1 with 2.6.1 to check if it works, but did not seem to work either.

Hence for now will be including libphonenumber 7.1.1 in my application, which works without any issue with protobuf 2.4.1.

Hope to see the fix soon in newer versions.

**Comment by keghani** [comment]
@venkyarya 2.6.1 from Maven Central does not have javanano. You can see more about that issue in #913.

The 2.6.1 that we use (that does have javanano) is from sources at [external/protobuf](https://android.googlesource.com/platform/external/protobuf/+/master). See [java/lib/](https://github.com/googlei18n/libphonenumber/tree/master/java/lib/com/google/protobuf/protobuf-java) for our copy.

I don't know how you're using libphonenumber. If you're taking it directly from Maven Central, version 7.2.6 should just work. We haven't heard from others having this issue since 7.2.1, so I would guess it's due to your setup. Since it's different from this issue (which is closed), if you need help please file a separate issue - otherwise other developers who can help with your setup may miss it.
