### ISSUE TITLE
Standards of metadata 

### ISSUE THREAD

**Issue by Saaha** [googlei18n/libphonenumber#917]
Hello there,

I was looking for a documentation about *metadata* which indicates if there is a standard used in the parsing of phone numbers ? Is there a RFC or anything else that legitimates the formats used ? 
Regarding the country code, it respects the  **ISO 3166-1 alpha-2** country. I am just wondering about the same thing about format numbers ? 
In this case, is there a document to refer to which contains all formats allowed by country ?

Thank you !

**Comment by penmetsaa** [comment]
@Philippe 

There is no universal standard to parse phone number. 
Each country (or even each telecom) can follow its own. You can find these rules in PhoneNumberMetadata.xml

Documentation about PhoneNumberMetadata.xml can be found here.
https://github.com/googlei18n/libphonenumber/blob/master/resources/phonemetadata.proto

PhoneNumberMetadata.xml file contains all formats and ranges that are supported.

There is no separate document which lists the ranges and formats that are supported for a given country.

Please let us know if you have any more questions.

Thanks & Regards,
Aravind

**Comment by Saaha** [comment]
Thank you for your answer.

I think I did not correctly describe my thoughts. 
Actually, I was wondering about *PhoneNumberMetadata.xml* : what I understood is this file is filled in with all known information for each telecom/country. But there is not a RFC which indicates where these data comes from. It's like looking for information in wikipedia. Not a blame but I believed there was a universal standard about format (by country/tel) necessarily communicate by country/tel.

**Comment by dlyongemallo** [comment]
In theory, phone numbering plans are all supposed to be administered through the ITU. Many countries' phone numbering plans may be found here:
http://www.itu.int/oth/T0202.aspx?parent=T0202

Not every country files their numbering plans with the ITU nor are the plans filed with ITU always up to date. In some countries, the numbering plans are directly handled by a government authority, while in others, most of the work is done by telecom companies (the government's role being only to distribute ranges at the prefix level, with the actual partitioning within the prefix done by the telecom).

A large part of the data in PhoneNumberMetadata.xml comes from the ITU documents, but because they're sometimes insufficient, we also include data from other sources.

There is no RFC indicating where the data comes from, or what format they're in. The specific format (regular expressions) used in PhoneNumberMetadata.xml right now is just an implementation detail of our library, which is subject to change.

Does that clarify things for you?

**Comment by Saaha** [comment]
Sure, that what I wanted ! 
Thank you for the explanation, 

Have a good day, Regards
