### ISSUE TITLE
Addition of non-geographic M2M MSISDN range

### ISSUE THREAD

**Issue by Gastomagic** [googlei18n/libphonenumber#930]
Hello,

I am the M2M operations manager for JTGlobal - an MNO based in the UK.

Is it please possible to add the +88236XXXXXXXXXX (15 digits) to the library
The range is provided by the ITU for global services.

In order to have your library properly updated is it not best for you to liaise with the GSMA and the ITU - given that they are those responsible in general? New ranges are released on IR21 documents from all MNOs and should be passed to the library as a matter of course to avoid service disruption of those services replying on your library. Seems disconnected to me.

Thanks

TG

**Comment by padmaksha** [comment]
Hi ,

Thanks for reporting the issue and your suggestions. 

The phonenumber library is currently aimed at cases where numbers can be dialed to reach a human endpoint.  We will have to look carefully at whether it's ok to add M2M (machine to machine)  numbers without breaking existing users. If we say M2M numbers as valid people assume that it’s going to reach a human.
We have no plans to support M2M numbers at the moment, but might in the future. 
Currently we do use  ITU updates and IR21 documents from the users to update the metadata in the library. At this moment we do not have any direct connections with GSMA or ITU.

**Comment by Gastomagic** [comment]
Hello there

Thanks for your reply.

I understand your stance – however my attention was only drawn to the library as a number of large SMS integrators (e.g Twilio) use your library as a reference point.
That being the case this ability of physically dial a human at the other end doesn’t really stack up.

Many types of MSISDN are not diallable but the numbers are still valid and given the way your library is being used by developers / integrators (rightly or wrongly) the ranges really need to be included.

If you would like me to intro you to some useful contacts at any of the global associations please let me know – otherwise it seems you are just waiting for someone to complain as a number range not working in order to fix it – rather than being proactive and adding them as they are released by the industry.

Thanks

TG

**Comment by lararennie** [comment]
Hi! Thanks for raising this issue.

One of the reasons we haven't supported M2M previously is because no one could explain their use to us sufficiently. You're quite correct: we don't require that a number has a human at the other end since we accept premium rate services and they might go to an automated system instead - but to date we only accept ranges that a human might call or send an SMS to. 

You mention SMS integrators above: do you mean that they should accept M2M numbers because they can be used for SMS? Can you explain what kinds of use-cases fail because we don't allow these numbers?

Many people use this library for formatting the numbers of their contacts, for allowing people to sign up for services, for working out how to dial someone in a different country, for working out what kind of cost might be associated with a number in an advert etc. I don't think the lack of M2M support hinders any of those use-cases - but I might be wrong?

Anyway more information on this issue would be welcomed!

Re your other point of proactive vs reactive - we do try and be proactive, but it's not always possible while keeping this a free and open-source service. If you know anyone from industry who is able to share updates with us we would love an intro, thanks!

Lara

**Comment by andyst** [comment]
See:
https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#what-about-m2m-machine-to-machine-numbers

**Comment by andyst** [comment]
Closing for now since there wasn't an update since December. Please reopen if you'd like to investigate support for M2M in libphonenumber. See the points we raise in the FAQ (mostly what Lara mentioned).

Thanks!

**Comment by Gastomagic** [comment]
hi Andy

I would like to reopen - can anyone tell me what I need to get the range added to the library? What information is required?

the biggest problem I have is that Twilio use your library - and I have many clients that use the Twilio service for sending shoulder taps and configuration messages via SMS to their SIMs / devices. There are countless applications for M2M of course.

I've suggested that Twilio make a manual addition to their own numbering scheme but they're admanat they follow your library - despite it being incomplete.

This essentially leads to me having to reprovision services with +447 numbers (which are in extremely short supply).

Any wisdom appreciated

TG

**Comment by andyst** [comment]
Hi TG,

Please start by responding to Lara's questions and the additional points made in the FAQ.

As explained, this is not a trivial change and can't be made quickly / lightly as it has the potential to change the semantics of existing API methods and these concerns need to be discussed / addressed.

Thanks,
Andy

**Comment by andyst** [comment]
Hi TG,

I missed that there's another issue to discuss M2M in general. Let's close this specific request for now (we did that for other country / carrier / range specific M2M requests too) and continue the discussion at #680 .

Please contribute to that other thread.

Thanks!
Andy
