### ISSUE TITLE
Denmark phoneNumberType issue

### ISSUE THREAD

**Issue by Cgen37** [googlei18n/libphonenumber#953]
Hello,

It seems that the pattern used to differentiate mobile and fixed line is incorrect because they are similar. 
I did some research and I found this 
* Mobile phones :
20-xx-xx-xx – 31-xx-xx-xx
40-xx-xx-xx – 42-xx-xx-xx
50-xx-xx-xx – 53-xx-xx-xx
60-xx-xx-xx – 61-xx-xx-xx
71-xx-xx-xx
81-xx-xx-xx
91-xx-xx-xx – 93-xx-xx-xx
* Landlines : 
32-xx-xx-xx – 36-xx-xx-xx
38-xx-xx-xx – 39-xx-xx-xx
43-xx-xx-xx – 49-xx-xx-xx
54-xx-xx-xx – 59-xx-xx-xx
62-xx-xx-xx – 66-xx-xx-xx
69-xx-xx-xx
72-xx-xx-xx – 79-xx-xx-xx
82-xx-xx-xx
86-xx-xx-xx – 89-xx-xx-xx
96-xx-xx-xx – 99-xx-xx-xx

thanks

**Comment by keghani** [comment]
Hi @Cgen37 

Can you say more about the research you used? Please see our [guidelines](https://github.com/googlei18n/libphonenumber/blob/master/CONTRIBUTING.md#provide-supporting-evidence).

**Comment by Cgen37** [comment]
Hi, Thanks you for your reactivity. 
I found information in this website : https://en.wikipedia.org/wiki/Telephone_numbers_in_Denmark

**Comment by keghani** [comment]
Thanks for sharing the link!

We have categorized the same ranges for both fixed-line and mobile because the official documentation from Denmark classifies these as "mainly" mobile or fixed-line, but not all one or the other. See official documentation: https://erhvervsstyrelsen.dk/sites/default/files/8-cifrede_abonnentnumre.xls, these are all "mainly" mobile or fixed-line.

The library is working as intended, we do not want to stop supporting these numbers as valid both for mobile and fixed-line. Thanks for reporting, please let us know if you find other issues!
