### ISSUE TITLE
google phone library override pattern

### ISSUE THREAD

**Issue by alokragate** [googlei18n/libphonenumber#979]
I was using version 7.0.5 and was able to override the pattern, using the below code, but I am not able to this after upgrading to 7.2.5 . Can you tell me how can we achieve this in the latest version.
```

NumberFormat newNumFormat = new NumberFormat();

newNumFormat.setPattern("(\\d{3})(\\d{3})(\\d*)");
newNumFormat.setFormat("$1 $2 $3");


List<NumberFormat> newNumberFormats = new ArrayList<NumberFormat>();
newNumberFormats.add(newNumFormat);

String   formattedNumber = phoneUtil.formatByPattern(phoneNumber, PhoneNumberFormat.NATIONAL, newNumberFormats);
```

Can you please help?

**Comment by keghani** [comment]
Hi @alokragate,

First, I want to stress that Phonemetadata is implementation-specific and not part of the public API. We can't guarantee that its behavior won't change. You should use the public API unless you're developing something else. If you find issues such as incorrect or outdated patterns, please let us know so we fix it upstream.

As for the new behavior, you can always check the release notes at [java/release_notes.txt](https://github.com/googlei18n/libphonenumber/blob/master/java/release_notes.txt).

You can see that as of 7.2 we're generating Phonemetadata as nanoproto. This is used differently than regular protocol buffers. You can read more about nanoproto [here](https://github.com/google/protobuf/tree/master/javanano), and see [our code](https://github.com/googlei18n/libphonenumber/tree/master/java/libphonenumber/src/com/google/i18n/phonenumbers) for examples of usage.

I hope that answers your question! Please re-open if you have further questions as we may miss the issue otherwise.
